export const MONSTER_MOBILITY = {
  LOCAL: "local",
  ROAMING: "roaming",
  RELENTLESS: "relentless",
};

export const MONSTER_MOBILITY_LABELS = {
  [MONSTER_MOBILITY.LOCAL]: "Reviertreu",
  [MONSTER_MOBILITY.ROAMING]: "Mobil",
  [MONSTER_MOBILITY.RELENTLESS]: "Jagdend",
};

export const MONSTER_RETREAT_PROFILE = {
  NONE: "none",
  CAUTIOUS: "cautious",
  COWARDLY: "cowardly",
};

export const MONSTER_RETREAT_LABELS = {
  [MONSTER_RETREAT_PROFILE.NONE]: "Standhaft",
  [MONSTER_RETREAT_PROFILE.CAUTIOUS]: "Vorsichtig",
  [MONSTER_RETREAT_PROFILE.COWARDLY]: "Fluchtbereit",
};

export const MONSTER_HEALING_PROFILE = {
  NONE: "none",
  SLOW: "slow",
  STEADY: "steady",
  LURKING: "lurking",
};

export const MONSTER_HEALING_LABELS = {
  [MONSTER_HEALING_PROFILE.NONE]: "Keine",
  [MONSTER_HEALING_PROFILE.SLOW]: "Langsam",
  [MONSTER_HEALING_PROFILE.STEADY]: "Stetig",
  [MONSTER_HEALING_PROFILE.LURKING]: "Nur außerhalb des Kampfes",
};

export const MONSTER_CATALOG = [
  {
    id: "bates",
    name: "Norman Bates",
    rank: 1,
    behavior: "dormant",
    behaviorLabel: "Schläfer",
    description: "Wirkt harmlos und unscheinbar, wird nach einem Angriff jedoch plötzlich tödlich.",
    strength: 3,
    precision: 4,
    reaction: 3,
    nerves: 3,
    intelligence: 5,
    hp: 10,
    xpReward: 12,
    aggroRadius: 2,
    canOpenDoors: true,
    special: "Wird erst nach einem Angriff wirklich aggressiv.",
  },
  {
    id: "motel-shlurfer",
    name: "Motel-Schlurfer",
    rank: 1,
    behavior: "wanderer",
    behaviorLabel: "Schlurfer",
    description: "Ein verwahrloster Schrecken aus schmutzigen Fluren und vergessenen Zimmern.",
    strength: 2,
    precision: 2,
    reaction: 2,
    nerves: 1,
    intelligence: 2,
    hp: 7,
    xpReward: 6,
    aggroRadius: 3,
    canOpenDoors: true,
    special: "Wirkt träge, rückt in engen Gängen aber hartnäckig nach.",
  },
  {
    id: "kellerkriecher",
    name: "Kellerkriecher",
    rank: 1,
    behavior: "wanderer",
    behaviorLabel: "Kriecher",
    description: "Ein huschender Schrecken aus dem Dunkel, der lieber aus Winkeln angreift.",
    strength: 1,
    precision: 3,
    reaction: 3,
    nerves: 1,
    intelligence: 1,
    hp: 6,
    xpReward: 6,
    aggroRadius: 3,
    canOpenDoors: false,
    special: "Ist in engen Räumen und Ecken besonders unangenehm.",
  },

  {
    id: "ghostface",
    name: "Ghostface",
    rank: 2,
    behavior: "stalker",
    behaviorLabel: "Verfolger",
    description: "Nimmt früh die Spur auf und lässt von seiner Beute meist nicht mehr ab.",
    strength: 4,
    precision: 5,
    reaction: 5,
    nerves: 3,
    intelligence: 4,
    hp: 12,
    xpReward: 15,
    aggroRadius: 8,
    offHand: "clapperboard-shield",
    canOpenDoors: true,
    special: "Bleibt früh an seiner Beute dran und fängt Hiebe mit seinem Rig ab.",
  },
  {
    id: "maskierter-nachahmer",
    name: "Maskierter Nachahmer",
    rank: 2,
    behavior: "stalker",
    behaviorLabel: "Verfolger",
    description: "Ein billiger Slasher-Abklatsch, der früh Druck macht und selten locker lässt.",
    strength: 2,
    precision: 3,
    reaction: 3,
    nerves: 2,
    intelligence: 2,
    hp: 8,
    xpReward: 8,
    aggroRadius: 6,
    canOpenDoors: true,
    special: "Nimmt früh die Verfolgung auf.",
  },
  {
    id: "videotheken-stalker",
    name: "Videotheken-Stalker",
    rank: 2,
    behavior: "stalker",
    behaviorLabel: "Jäger",
    description: "Zwischen Filmplakaten und Staubregalen wirkt er fehl am Platz – bis er lossprintet.",
    strength: 2,
    precision: 3,
    reaction: 4,
    nerves: 2,
    intelligence: 2,
    hp: 8,
    xpReward: 8,
    aggroRadius: 5,
    canOpenDoors: true,
    special: "Reagiert schnell auf Sichtkontakt.",
  },

  {
    id: "chucky",
    name: "Chucky",
    rank: 3,
    behavior: "wanderer",
    behaviorLabel: "Wirrling",
    description: "Klein, flink und nervtötend unberechenbar.",
    strength: 4,
    precision: 5,
    reaction: 6,
    nerves: 2,
    intelligence: 4,
    hp: 11,
    xpReward: 18,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Bewegt sich häufig unberechenbar und erstaunlich flink.",
  },
  {
    id: "besessene-puppe",
    name: "Besessene Puppe",
    rank: 3,
    behavior: "wanderer",
    behaviorLabel: "Wirrling",
    description: "Klein, hektisch und schwer einzuschätzen, wenn sie erst einmal in Bewegung ist.",
    strength: 2,
    precision: 3,
    reaction: 4,
    nerves: 1,
    intelligence: 2,
    hp: 7,
    xpReward: 10,
    aggroRadius: 4,
    canOpenDoors: false,
    special: "Bewegt sich oft unvorhersehbar.",
  },
  {
    id: "gremlin",
    name: "Gremlin",
    rank: 3,
    behavior: "trickster",
    behaviorLabel: "Störenfried",
    description: "Ein kicherndes Sabotagevieh, das mehr Chaos anrichtet, als seine Größe vermuten lässt.",
    strength: 2,
    precision: 3,
    reaction: 4,
    nerves: 1,
    intelligence: 2,
    hp: 8,
    xpReward: 10,
    aggroRadius: 4,
    canOpenDoors: false,
    special: "Wechselt gern abrupt die Richtung und stört den Kampfablauf.",
  },

  {
    id: "myers",
    name: "Michael Myers",
    rank: 4,
    behavior: "juggernaut",
    behaviorLabel: "Unerbittlich",
    description: "Langsam, schweigsam und von bedrückender Beharrlichkeit.",
    strength: 7,
    precision: 4,
    reaction: 3,
    nerves: 5,
    intelligence: 3,
    hp: 20,
    xpReward: 24,
    aggroRadius: 7,
    canOpenDoors: false,
    special: "Regeneriert langsam, wenn er längere Zeit nicht getroffen wird.",
  },
  {
    id: "stummer-maskenträger",
    name: "Stummer Maskenträger",
    rank: 4,
    behavior: "juggernaut",
    behaviorLabel: "Unerbittlich",
    description: "Schweigsam, langsam und mit genau der Art von Präsenz, die Korridore leer macht.",
    strength: 4,
    precision: 2,
    reaction: 2,
    nerves: 3,
    intelligence: 1,
    hp: 13,
    xpReward: 13,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Setzt stetig nach, wenn er dich einmal gesehen hat.",
  },
  {
    id: "friedhofsschlurfer",
    name: "Friedhofsschlurfer",
    rank: 4,
    behavior: "juggernaut",
    behaviorLabel: "Untoter",
    description: "Ein schwerfälliger Untoter, der weniger jagt als einfach immer näher kommt.",
    strength: 4,
    precision: 2,
    reaction: 1,
    nerves: 3,
    intelligence: 1,
    hp: 14,
    xpReward: 13,
    aggroRadius: 4,
    canOpenDoors: false,
    special: "Besonders zäh für seine Stufe.",
  },

  {
    id: "jason",
    name: "Jason Voorhees",
    rank: 5,
    behavior: "juggernaut",
    behaviorLabel: "Schlächter",
    description: "Zäh, schwer zu stoppen und im Nahkampf brutal.",
    strength: 8,
    precision: 4,
    reaction: 3,
    nerves: 5,
    intelligence: 3,
    hp: 22,
    xpReward: 28,
    aggroRadius: 7,
    canOpenDoors: false,
    special: "Rückt stoisch und ohne Hast näher.",
  },
  {
    id: "camp-schlaechter",
    name: "Camp-Schlächter",
    rank: 5,
    behavior: "juggernaut",
    behaviorLabel: "Schlächter",
    description: "Ein roher Killer aus Lagerfeuerlegenden und Blutspuren im Unterholz.",
    strength: 5,
    precision: 3,
    reaction: 2,
    nerves: 3,
    intelligence: 1,
    hp: 15,
    xpReward: 16,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Im Nahkampf gefährlicher als auf Distanz.",
  },
  {
    id: "mutierter-hinterwaeldler",
    name: "Mutierter Hinterwäldler",
    rank: 5,
    behavior: "juggernaut",
    behaviorLabel: "Brecher",
    description: "Mehr rohe Masse als Mensch – laut, brutal und schwer kleinzukriegen.",
    strength: 5,
    precision: 2,
    reaction: 2,
    nerves: 3,
    intelligence: 1,
    hp: 16,
    xpReward: 16,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Hält spürbar mehr aus als andere Gegner seiner Stufe.",
  },

  {
    id: "freddy",
    name: "Freddy Krüger",
    rank: 6,
    behavior: "stalker",
    behaviorLabel: "Jäger",
    description: "Clever, boshaft und überraschend aggressiv, sobald er Druck wittert.",
    strength: 6,
    precision: 6,
    reaction: 5,
    nerves: 4,
    intelligence: 6,
    hp: 18,
    xpReward: 32,
    aggroRadius: 9,
    offHand: "neon-diner-tray",
    canOpenDoors: true,
    special: "Führt seine Klauen mit einer improvisierten Boiler-Platte als Schutz.",
  },
  {
    id: "traumwandler",
    name: "Traumwandler",
    rank: 6,
    behavior: "stalker",
    behaviorLabel: "Jäger",
    description: "Eine flackernde Gestalt, die sich anfühlt, als käme sie aus einem schlechten Traum.",
    strength: 4,
    precision: 4,
    reaction: 4,
    nerves: 3,
    intelligence: 4,
    hp: 13,
    xpReward: 20,
    aggroRadius: 7,
    canOpenDoors: true,
    special: "Taucht plötzlich auf und setzt dann sofort nach.",
  },
  {
    id: "kesselraum-peiniger",
    name: "Kesselraum-Peiniger",
    rank: 6,
    behavior: "stalker",
    behaviorLabel: "Peiniger",
    description: "Schweiß, Dampf und Metall begleiten diesen Jäger auf Schritt und Tritt.",
    strength: 4,
    precision: 4,
    reaction: 3,
    nerves: 3,
    intelligence: 4,
    hp: 14,
    xpReward: 20,
    aggroRadius: 7,
    canOpenDoors: true,
    special: "Bleibt in mittlerer Distanz hartnäckig auf dem Ziel.",
  },

  {
    id: "pennywise",
    name: "Pennywise",
    rank: 7,
    behavior: "trickster",
    behaviorLabel: "Trickser",
    description: "Spielt mit Distanz, Verunsicherung und plötzlichen Ausbrüchen von Gewalt.",
    strength: 6,
    precision: 5,
    reaction: 5,
    nerves: 5,
    intelligence: 7,
    hp: 21,
    xpReward: 38,
    aggroRadius: 7,
    canOpenDoors: true,
    special: "Erholt sich leicht, wenn er sich aus dem direkten Kampf löst.",
  },
  {
    id: "kanalclown",
    name: "Kanalclown",
    rank: 7,
    behavior: "trickster",
    behaviorLabel: "Trickser",
    description: "Ein grinsender Schrecken, der Unsicherheit fast ebenso gut einsetzt wie Gewalt.",
    strength: 4,
    precision: 4,
    reaction: 4,
    nerves: 4,
    intelligence: 5,
    hp: 15,
    xpReward: 24,
    aggroRadius: 5,
    canOpenDoors: true,
    special: "Löst sich leichter aus dem direkten Schlagabtausch.",
  },
  {
    id: "gestaltlaeufer",
    name: "Gestaltläufer",
    rank: 7,
    behavior: "trickster",
    behaviorLabel: "Irrbild",
    description: "Nie ganz dort, wo man ihn erwartet, und nie so harmlos, wie er kurz wirkt.",
    strength: 4,
    precision: 4,
    reaction: 5,
    nerves: 3,
    intelligence: 5,
    hp: 14,
    xpReward: 24,
    aggroRadius: 5,
    canOpenDoors: true,
    special: "Wechselt gern zwischen Annäherung und Rückzug.",
  },

  {
    id: "xenomorph",
    name: "Xenomorph",
    rank: 8,
    behavior: "stalker",
    behaviorLabel: "Raubtier",
    description: "Extrem schnell und in engen Gängen nahezu pausenlos auf Jagd.",
    strength: 8,
    precision: 6,
    reaction: 7,
    nerves: 3,
    intelligence: 4,
    hp: 22,
    xpReward: 45,
    aggroRadius: 10,
    canOpenDoors: false,
    special: "Sehr weite Wahrnehmung und aggressive Jagd.",
  },
  {
    id: "critter",
    name: "Critter",
    rank: 8,
    behavior: "stalker",
    behaviorLabel: "Beißer",
    description: "Klein, schnell und mit viel zu vielen Zähnen für seine Größe.",
    strength: 5,
    precision: 4,
    reaction: 5,
    nerves: 2,
    intelligence: 2,
    hp: 15,
    xpReward: 28,
    aggroRadius: 7,
    canOpenDoors: false,
    special: "Greift aggressiv an, sobald er Beute wittert.",
  },
  {
    id: "tunnelkriecher",
    name: "Tunnelkriecher",
    rank: 8,
    behavior: "stalker",
    behaviorLabel: "Raubtier",
    description: "Ein dürrer Jäger aus Schächten und Lüftungsgängen, schnell und unangenehm leise.",
    strength: 5,
    precision: 4,
    reaction: 5,
    nerves: 2,
    intelligence: 2,
    hp: 16,
    xpReward: 28,
    aggroRadius: 8,
    canOpenDoors: false,
    special: "Hat eine weite Wahrnehmung in engen Bereichen.",
  },

  {
    id: "predator",
    name: "Predator",
    rank: 9,
    behavior: "hunter",
    behaviorLabel: "Jagdprofi",
    description: "Beobachtet erst, wählt dann den Moment und schlägt präzise zu.",
    strength: 9,
    precision: 7,
    reaction: 6,
    nerves: 5,
    intelligence: 7,
    hp: 24,
    xpReward: 52,
    aggroRadius: 9,
    offHand: "satellite-dish-guard",
    canOpenDoors: true,
    special: "Trägt einen Jagdschutz am Arm und jagt zielstrebig.",
  },
  {
    id: "trophaeenjaeger",
    name: "Trophäenjäger",
    rank: 9,
    behavior: "hunter",
    behaviorLabel: "Jagdprofi",
    description: "Ein disziplinierter Killer, der seine Ziele beobachtet wie Beute.",
    strength: 6,
    precision: 5,
    reaction: 4,
    nerves: 4,
    intelligence: 5,
    hp: 18,
    xpReward: 34,
    aggroRadius: 6,
    canOpenDoors: true,
    special: "Nähert sich kontrolliert und greift erst im richtigen Moment an.",
  },
  {
    id: "soeldner-tracker",
    name: "Söldner-Tracker",
    rank: 9,
    behavior: "hunter",
    behaviorLabel: "Tracker",
    description: "Weniger Show, mehr Professionalität – ein kalter Verfolger mit sicherer Hand.",
    strength: 6,
    precision: 5,
    reaction: 4,
    nerves: 3,
    intelligence: 5,
    hp: 18,
    xpReward: 34,
    aggroRadius: 6,
    canOpenDoors: true,
    special: "Bleibt auf Distanz aufmerksam und drückt dann gezielt nach.",
  },

  {
    id: "vader",
    name: "Darth Vader",
    rank: 10,
    behavior: "hunter",
    behaviorLabel: "Dunkler Lord",
    description: "Ein spätes Elite-Monster mit eisiger Ruhe und überwältigender Präsenz.",
    strength: 11,
    precision: 7,
    reaction: 5,
    nerves: 6,
    intelligence: 8,
    hp: 29,
    xpReward: 68,
    aggroRadius: 11,
    canOpenDoors: true,
    special: "Jagt kalt, direkt und mit eiserner Disziplin.",
  },
  {
    id: "dunkler-vollstrecker",
    name: "Dunkler Vollstrecker",
    rank: 10,
    behavior: "hunter",
    behaviorLabel: "Vollstrecker",
    description: "Ein schwerer Elitegegner mit kalter Haltung und tödlicher Konsequenz.",
    strength: 8,
    precision: 5,
    reaction: 4,
    nerves: 5,
    intelligence: 6,
    hp: 21,
    xpReward: 44,
    aggroRadius: 8,
    canOpenDoors: true,
    special: "Setzt mit disziplinierter Härte nach.",
  },
  {
    id: "sternen-inquisitor",
    name: "Sternen-Inquisitor",
    rank: 10,
    behavior: "hunter",
    behaviorLabel: "Inquisitor",
    description: "Ruhig, kontrolliert und mit jener Autorität, die jeden Raum sofort verändert.",
    strength: 7,
    precision: 6,
    reaction: 4,
    nerves: 5,
    intelligence: 6,
    hp: 20,
    xpReward: 44,
    aggroRadius: 8,
    canOpenDoors: true,
    special: "Jagt ohne Hast, aber ohne jeden Zweifel.",
  },

  {
    id: "terminator",
    name: "Terminator",
    rank: 11,
    behavior: "hunter",
    behaviorLabel: "Unaufhaltsam",
    description: "Kalte Maschine, die sich nicht abschütteln lässt und jeden Fehler bestraft.",
    strength: 12,
    precision: 6,
    reaction: 4,
    nerves: 6,
    intelligence: 7,
    hp: 34,
    xpReward: 84,
    aggroRadius: 12,
    canOpenDoors: true,
    special: "Kann dir als einziger Gegner über Treppen auf andere Ebenen folgen.",
    canChangeFloors: true,
  },
  {
    id: "killerdrohne",
    name: "Killerdrohne",
    rank: 11,
    behavior: "hunter",
    behaviorLabel: "Maschine",
    description: "Präzise, kalt und frei von jedem Zögern – eher Protokoll als Persönlichkeit.",
    strength: 8,
    precision: 5,
    reaction: 4,
    nerves: 5,
    intelligence: 5,
    hp: 24,
    xpReward: 56,
    aggroRadius: 9,
    canOpenDoors: true,
    special: "Verfolgt Ziele zuverlässig und ohne Ermüdung.",
  },
  {
    id: "cyborg-vollstrecker",
    name: "Cyborg-Vollstrecker",
    rank: 11,
    behavior: "juggernaut",
    behaviorLabel: "Unaufhaltsam",
    description: "Mehr Metall als Mensch und nur einem Auftrag verpflichtet.",
    strength: 9,
    precision: 4,
    reaction: 3,
    nerves: 5,
    intelligence: 5,
    hp: 25,
    xpReward: 56,
    aggroRadius: 8,
    canOpenDoors: true,
    special: "Rückt stoisch vor und lässt sich kaum abschütteln.",
  },
];

