export const MONSTER_MOBILITY = {
  LOCAL: "local",
  ROAMING: "roaming",
  RELENTLESS: "relentless",
};

import { PHASE_ONE_STANDARD_MONSTERS } from "./monster-phase-one.mjs";

export const MONSTER_MOBILITY_LABELS = {
  [MONSTER_MOBILITY.LOCAL]: "Reviertreu",
  [MONSTER_MOBILITY.ROAMING]: "Mobil",
  [MONSTER_MOBILITY.RELENTLESS]: "Jagdend",
};

export const MONSTER_RETREAT_PROFILE = {
  NONE: "none",
  CAUTIOUS: "cautious",
  COWARDLY: "cowardly",
};

export const MONSTER_RETREAT_LABELS = {
  [MONSTER_RETREAT_PROFILE.NONE]: "Standhaft",
  [MONSTER_RETREAT_PROFILE.CAUTIOUS]: "Vorsichtig",
  [MONSTER_RETREAT_PROFILE.COWARDLY]: "Fluchtbereit",
};

export const MONSTER_HEALING_PROFILE = {
  NONE: "none",
  SLOW: "slow",
  STEADY: "steady",
  LURKING: "lurking",
};

export const MONSTER_HEALING_LABELS = {
  [MONSTER_HEALING_PROFILE.NONE]: "Keine",
  [MONSTER_HEALING_PROFILE.SLOW]: "Langsam",
  [MONSTER_HEALING_PROFILE.STEADY]: "Stetig",
  [MONSTER_HEALING_PROFILE.LURKING]: "Nur außerhalb des Kampfes",
};

export const MONSTER_TEMPERAMENT = {
  STOIC: "stoic",
  PATROL: "patrol",
  RESTLESS: "restless",
  ERRATIC: "erratic",
};

export const MONSTER_TEMPERAMENT_VALUES = Object.freeze([
  MONSTER_TEMPERAMENT.STOIC,
  MONSTER_TEMPERAMENT.PATROL,
  MONSTER_TEMPERAMENT.RESTLESS,
  MONSTER_TEMPERAMENT.ERRATIC,
]);

export const MONSTER_TEMPERAMENT_HINTS = Object.freeze({
  [MONSTER_TEMPERAMENT.STOIC]: Object.freeze([
    "Regt sich kaum, bis etwas seine stille Geduld stört.",
    "Steht da, als hätte der Raum längst beschlossen, ihm zu gehören.",
    "Jede Bewegung wirkt sparsam und endgültig.",
    "Bleibt oft stehen, als würde es den Moment abwarten statt ihn suchen.",
    "Wirkt, als könne es stundenlang dieselbe Stelle bewachen.",
    "Lässt sich Zeit und macht gerade dadurch nervös.",
    "Hält den Blick länger als angenehm auf demselben Punkt.",
    "Rührt sich selten ohne Grund, aber nie ziellos.",
    "Trägt eine kalte Ruhe in jede Ecke, die es betritt.",
    "Scheint weder Eile noch Zweifel zu kennen.",
  ]),
  [MONSTER_TEMPERAMENT.PATROL]: Object.freeze([
    "Zieht Bahnen, als folge es einem längst einstudierten Ablauf.",
    "Prüft Zugänge mit einer beunruhigenden Routine.",
    "Wirkt, als zähle es Räume statt Schritte.",
    "Kehrt mit methodischer Ruhe immer wieder auf ähnliche Wege zurück.",
    "Beobachtet Türen und Übergänge mit fast dienstlicher Genauigkeit.",
    "Bewegt sich kontrolliert, als hätte alles hier seinen vorgesehenen Platz.",
    "Mustert den Raum wie ein stiller Wachgang auf Endlosschleife.",
    "Nimmt Ecken und Durchgänge wahr, als wären sie Punkte auf einer Liste.",
    "Wandert nicht planlos, sondern wie nach einem stummen Protokoll.",
    "Sein Rhythmus wirkt eingeübt und dadurch umso unheimlicher.",
  ]),
  [MONSTER_TEMPERAMENT.RESTLESS]: Object.freeze([
    "Scheint es kaum auszuhalten, länger am selben Ort zu bleiben.",
    "Zuckt ständig in die nächste Bewegung hinein.",
    "Sucht Übergänge, Flure und offene Wege mit rastloser Energie.",
    "Wirkt, als würde es jeden Raum nur auf dem Sprung betreten.",
    "Läuft, als wäre Stillstand die eigentliche Bedrohung.",
    "Hat etwas Hetzendes, selbst wenn es gerade nicht jagt.",
    "Drängt immer weiter, als würde hinter ihm etwas nachsetzen.",
    "Nimmt den direkten Weg nur, um schneller schon wieder woanders zu sein.",
    "Kann kaum still wirken, selbst wenn es innehält.",
    "Trägt eine nervöse Vorwärtswucht in jede Bewegung.",
  ]),
  [MONSTER_TEMPERAMENT.ERRATIC]: Object.freeze([
    "Seine Aufmerksamkeit springt, ohne dass man den Auslöser versteht.",
    "Wirkt, als folge es Eingebungen, die nur für einen Moment Sinn ergeben.",
    "Zögert kurz, nur um im nächsten Augenblick völlig anders zu reagieren.",
    "Lässt sich schwer lesen, als wechselten seine Impulse mitten im Schritt.",
    "Hat etwas Launisches, das jeden Weg unsicher erscheinen lässt.",
    "Bewegt sich nicht chaotisch, aber nie ganz berechenbar.",
    "Wirkt einen Moment lang orientiert und im nächsten sonderbar entrückt.",
    "Scheint auf unsichtbare Reize zu reagieren, die sonst niemand bemerkt.",
    "Sein Rhythmus kippt immer wieder in etwas Unvorhersehbares.",
    "Trägt eine unangenehme Spontaneität in sich, die nie ganz zufällig wirkt.",
  ]),
});

const MONSTER_GRAMMAR = {
  NAMED_MASCULINE: Object.freeze({ articleMode: "none", gender: "masculine" }),
  GENERIC_MASCULINE: Object.freeze({ articleMode: "indefinite", gender: "masculine" }),
  GENERIC_FEMININE: Object.freeze({ articleMode: "indefinite", gender: "feminine" }),
};

function createInflectableMonsterGrammar(profile, adjectiveStem, noun) {
  return {
    ...profile,
    inflectableParts: {
      adjectiveStem,
      noun,
    },
  };
}

function createMonsterAiProfile({
  mobility,
  retreatProfile,
  healingProfile,
  allowedTemperaments,
}) {
  return {
    mobility,
    mobilityLabel: MONSTER_MOBILITY_LABELS[mobility],
    retreatProfile,
    retreatLabel: MONSTER_RETREAT_LABELS[retreatProfile],
    healingProfile,
    healingLabel: MONSTER_HEALING_LABELS[healingProfile],
    allowedTemperaments: [...allowedTemperaments],
  };
}

export const LEGACY_STUDIO_SPECIAL_POOLS = Object.freeze({
  slasher: Object.freeze([
    "bates",
    "motel-shlurfer",
    "kellerkriecher",
    "ghostface",
    "maskierter-nachahmer",
    "videotheken-stalker",
    "chucky",
    "besessene-puppe",
    "gremlin",
    "myers",
    "stummer-maskentraeger",
    "friedhofsschlurfer",
    "jason",
    "camp-schlaechter",
    "mutierter-hinterwaeldler",
    "freddy",
    "traumwandler",
    "kesselraum-peiniger",
    "pennywise",
    "kanalclown",
    "gestaltlaeufer",
  ]),
  creature_feature: Object.freeze([
    "xenomorph",
    "critter",
    "tunnelkriecher",
  ]),
  action: Object.freeze([
    "predator",
    "trophaeenjaeger",
    "soeldner-tracker",
    "terminator",
    "killerdrohne",
    "cyborg-vollstrecker",
  ]),
  space_opera: Object.freeze([
    "vader",
    "dunkler-vollstrecker",
    "sternen-inquisitor",
  ]),
});

const LEGACY_SPECIAL_MONSTER_CONFIG_BY_ID = Object.freeze(
  Object.fromEntries(
    Object.entries(LEGACY_STUDIO_SPECIAL_POOLS).flatMap(([archetypeId, monsterIds]) =>
      monsterIds.map((monsterId) => [
        monsterId,
        Object.freeze({
          archetypeId,
          spawnGroup: "legacy_special",
          spawnWeight: 1,
        }),
      ])
    ),
  ),
);

function applyLegacySpecialPoolConfig(monster) {
  const config = LEGACY_SPECIAL_MONSTER_CONFIG_BY_ID[monster.id];
  if (!config) {
    return monster;
  }

  return {
    ...monster,
    archetypeId: config.archetypeId,
    spawnGroup: config.spawnGroup,
    spawnWeight: config.spawnWeight,
    legacySpecialPool: true,
  };
}

export const MONSTER_CATALOG = [
  {
    id: "bates",
    name: "Norman Bates",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 1,
    behavior: "dormant",
    behaviorLabel: "Schläfer",
    description: "Wirkt harmlos und unscheinbar, wird nach einem Angriff jedoch plötzlich tödlich.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.LOCAL,
      retreatProfile: MONSTER_RETREAT_PROFILE.CAUTIOUS,
      healingProfile: MONSTER_HEALING_PROFILE.LURKING,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 3,
    precision: 4,
    reaction: 3,
    nerves: 3,
    intelligence: 5,
    hp: 10,
    xpReward: 12,
    aggroRadius: 2,
    canOpenDoors: true,
    special: "Wird erst nach einem Angriff wirklich aggressiv.",
  },
  {
    id: "motel-shlurfer",
    name: "Motel-Schlurfer",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 1,
    behavior: "wanderer",
    behaviorLabel: "Schlurfer",
    description: "Ein verwahrloster Schrecken aus schmutzigen Fluren und vergessenen Zimmern.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.SLOW,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC, MONSTER_TEMPERAMENT.RESTLESS],
    }),
    strength: 2,
    precision: 2,
    reaction: 2,
    nerves: 1,
    intelligence: 2,
    hp: 7,
    xpReward: 6,
    aggroRadius: 3,
    canOpenDoors: true,
    special: "Wirkt träge, rückt in engen Gängen aber hartnäckig nach.",
  },
  {
    id: "kellerkriecher",
    name: "Kellerkriecher",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 1,
    behavior: "wanderer",
    behaviorLabel: "Kriecher",
    description: "Ein huschender Schrecken aus dem Dunkel, der lieber aus Winkeln angreift.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.LOCAL,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.NONE,
      allowedTemperaments: [MONSTER_TEMPERAMENT.RESTLESS, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 1,
    precision: 3,
    reaction: 3,
    nerves: 1,
    intelligence: 1,
    hp: 6,
    xpReward: 6,
    aggroRadius: 3,
    canOpenDoors: false,
    special: "Ist in engen Räumen und Ecken besonders unangenehm.",
  },

  {
    id: "ghostface",
    name: "Ghostface",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 2,
    behavior: "stalker",
    behaviorLabel: "Verfolger",
    description: "Nimmt früh die Spur auf und lässt von seiner Beute meist nicht mehr ab.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.CAUTIOUS,
      healingProfile: MONSTER_HEALING_PROFILE.STEADY,
      allowedTemperaments: [MONSTER_TEMPERAMENT.PATROL, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 4,
    precision: 5,
    reaction: 5,
    nerves: 3,
    intelligence: 4,
    hp: 12,
    xpReward: 15,
    aggroRadius: 8,
    offHand: "clapperboard-shield",
    canOpenDoors: true,
    special: "Bleibt früh an seiner Beute dran und fängt Hiebe mit seinem Rig ab.",
  },
  {
    id: "maskierter-nachahmer",
    name: "Maskierter Nachahmer",
    grammar: createInflectableMonsterGrammar(MONSTER_GRAMMAR.GENERIC_MASCULINE, "maskiert", "Nachahmer"),
    rank: 2,
    behavior: "stalker",
    behaviorLabel: "Verfolger",
    description: "Ein billiger Slasher-Abklatsch, der früh Druck macht und selten locker lässt.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.SLOW,
      allowedTemperaments: [MONSTER_TEMPERAMENT.PATROL, MONSTER_TEMPERAMENT.RESTLESS],
    }),
    strength: 2,
    precision: 3,
    reaction: 3,
    nerves: 2,
    intelligence: 2,
    hp: 8,
    xpReward: 8,
    aggroRadius: 6,
    canOpenDoors: true,
    special: "Nimmt früh die Verfolgung auf.",
  },
  {
    id: "videotheken-stalker",
    name: "Videotheken-Stalker",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 2,
    behavior: "stalker",
    behaviorLabel: "Jäger",
    description: "Zwischen Filmplakaten und Staubregalen wirkt er fehl am Platz – bis er lossprintet.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.SLOW,
      allowedTemperaments: [MONSTER_TEMPERAMENT.PATROL, MONSTER_TEMPERAMENT.RESTLESS],
    }),
    strength: 2,
    precision: 3,
    reaction: 4,
    nerves: 2,
    intelligence: 2,
    hp: 8,
    xpReward: 8,
    aggroRadius: 5,
    canOpenDoors: true,
    special: "Reagiert schnell auf Sichtkontakt.",
  },

  {
    id: "chucky",
    name: "Chucky",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 3,
    behavior: "wanderer",
    behaviorLabel: "Wirrling",
    description: "Klein, flink und nervtötend unberechenbar.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.COWARDLY,
      healingProfile: MONSTER_HEALING_PROFILE.STEADY,
      allowedTemperaments: [MONSTER_TEMPERAMENT.RESTLESS, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 4,
    precision: 5,
    reaction: 6,
    nerves: 2,
    intelligence: 4,
    hp: 11,
    xpReward: 18,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Bewegt sich häufig unberechenbar und erstaunlich flink.",
  },
  {
    id: "besessene-puppe",
    name: "Besessene Puppe",
    grammar: createInflectableMonsterGrammar(MONSTER_GRAMMAR.GENERIC_FEMININE, "besessen", "Puppe"),
    rank: 3,
    behavior: "wanderer",
    behaviorLabel: "Wirrling",
    description: "Klein, hektisch und schwer einzuschätzen, wenn sie erst einmal in Bewegung ist.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.LOCAL,
      retreatProfile: MONSTER_RETREAT_PROFILE.COWARDLY,
      healingProfile: MONSTER_HEALING_PROFILE.LURKING,
      allowedTemperaments: [MONSTER_TEMPERAMENT.RESTLESS, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 2,
    precision: 3,
    reaction: 4,
    nerves: 1,
    intelligence: 2,
    hp: 7,
    xpReward: 10,
    aggroRadius: 4,
    canOpenDoors: false,
    special: "Bewegt sich oft unvorhersehbar.",
  },
  {
    id: "gremlin",
    name: "Gremlin",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 3,
    behavior: "trickster",
    behaviorLabel: "Störenfried",
    description: "Ein kicherndes Sabotagevieh, das mehr Chaos anrichtet, als seine Größe vermuten lässt.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.COWARDLY,
      healingProfile: MONSTER_HEALING_PROFILE.NONE,
      allowedTemperaments: [MONSTER_TEMPERAMENT.RESTLESS, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 2,
    precision: 3,
    reaction: 4,
    nerves: 1,
    intelligence: 2,
    hp: 8,
    xpReward: 10,
    aggroRadius: 4,
    canOpenDoors: false,
    special: "Wechselt gern abrupt die Richtung und stört den Kampfablauf.",
  },

  {
    id: "myers",
    name: "Michael Myers",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 4,
    behavior: "juggernaut",
    behaviorLabel: "Unerbittlich",
    description: "Langsam, schweigsam und von bedrückender Beharrlichkeit.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.SLOW,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC],
    }),
    strength: 7,
    precision: 4,
    reaction: 3,
    nerves: 5,
    intelligence: 3,
    hp: 20,
    xpReward: 24,
    aggroRadius: 7,
    canOpenDoors: false,
    special: "Regeneriert langsam, wenn er längere Zeit nicht getroffen wird.",
  },
  {
    id: "stummer-maskentraeger",
    name: "Stummer Maskenträger",
    grammar: createInflectableMonsterGrammar(MONSTER_GRAMMAR.GENERIC_MASCULINE, "stumm", "Maskenträger"),
    rank: 4,
    behavior: "juggernaut",
    behaviorLabel: "Unerbittlich",
    description: "Schweigsam, langsam und mit genau der Art von Präsenz, die Korridore leer macht.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.SLOW,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC, MONSTER_TEMPERAMENT.PATROL],
    }),
    strength: 4,
    precision: 2,
    reaction: 2,
    nerves: 3,
    intelligence: 1,
    hp: 13,
    xpReward: 13,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Setzt stetig nach, wenn er dich einmal gesehen hat.",
  },
  {
    id: "friedhofsschlurfer",
    name: "Friedhofsschlurfer",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 4,
    behavior: "juggernaut",
    behaviorLabel: "Untoter",
    description: "Ein schwerfälliger Untoter, der weniger jagt als einfach immer näher kommt.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.SLOW,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC],
    }),
    strength: 4,
    precision: 2,
    reaction: 1,
    nerves: 3,
    intelligence: 1,
    hp: 14,
    xpReward: 13,
    aggroRadius: 4,
    canOpenDoors: false,
    special: "Besonders zäh für seine Stufe.",
  },

  {
    id: "jason",
    name: "Jason Voorhees",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 5,
    behavior: "juggernaut",
    behaviorLabel: "Schlächter",
    description: "Zäh, schwer zu stoppen und im Nahkampf brutal.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.STEADY,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC],
    }),
    strength: 8,
    precision: 4,
    reaction: 3,
    nerves: 5,
    intelligence: 3,
    hp: 22,
    xpReward: 28,
    aggroRadius: 7,
    canOpenDoors: false,
    special: "Rückt stoisch und ohne Hast näher.",
  },
  {
    id: "camp-schlaechter",
    name: "Camp-Schlächter",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 5,
    behavior: "juggernaut",
    behaviorLabel: "Schlächter",
    description: "Ein roher Killer aus Lagerfeuerlegenden und Blutspuren im Unterholz.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.NONE,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC, MONSTER_TEMPERAMENT.RESTLESS],
    }),
    strength: 5,
    precision: 3,
    reaction: 2,
    nerves: 3,
    intelligence: 1,
    hp: 15,
    xpReward: 16,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Im Nahkampf gefährlicher als auf Distanz.",
  },
  {
    id: "mutierter-hinterwaeldler",
    name: "Mutierter Hinterwäldler",
    grammar: createInflectableMonsterGrammar(MONSTER_GRAMMAR.GENERIC_MASCULINE, "mutiert", "Hinterwäldler"),
    rank: 5,
    behavior: "juggernaut",
    behaviorLabel: "Brecher",
    description: "Mehr rohe Masse als Mensch – laut, brutal und schwer kleinzukriegen.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.NONE,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC, MONSTER_TEMPERAMENT.RESTLESS],
    }),
    strength: 5,
    precision: 2,
    reaction: 2,
    nerves: 3,
    intelligence: 1,
    hp: 16,
    xpReward: 16,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Hält spürbar mehr aus als andere Gegner seiner Stufe.",
  },

  {
    id: "freddy",
    name: "Freddy Krüger",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 6,
    behavior: "stalker",
    behaviorLabel: "Jäger",
    description: "Clever, boshaft und überraschend aggressiv, sobald er Druck wittert.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.CAUTIOUS,
      healingProfile: MONSTER_HEALING_PROFILE.LURKING,
      allowedTemperaments: [MONSTER_TEMPERAMENT.PATROL, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 6,
    precision: 6,
    reaction: 5,
    nerves: 4,
    intelligence: 6,
    hp: 18,
    xpReward: 32,
    aggroRadius: 9,
    offHand: "neon-diner-tray",
    canOpenDoors: true,
    special: "Führt seine Klauen mit einer improvisierten Boiler-Platte als Schutz.",
  },
  {
    id: "traumwandler",
    name: "Traumwandler",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 6,
    behavior: "stalker",
    behaviorLabel: "Jäger",
    description: "Eine flackernde Gestalt, die sich anfühlt, als käme sie aus einem schlechten Traum.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.CAUTIOUS,
      healingProfile: MONSTER_HEALING_PROFILE.LURKING,
      allowedTemperaments: [MONSTER_TEMPERAMENT.PATROL, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 4,
    precision: 4,
    reaction: 4,
    nerves: 3,
    intelligence: 4,
    hp: 13,
    xpReward: 20,
    aggroRadius: 7,
    canOpenDoors: true,
    special: "Taucht plötzlich auf und setzt dann sofort nach.",
  },
  {
    id: "kesselraum-peiniger",
    name: "Kesselraum-Peiniger",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 6,
    behavior: "stalker",
    behaviorLabel: "Peiniger",
    description: "Schweiß, Dampf und Metall begleiten diesen Jäger auf Schritt und Tritt.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.CAUTIOUS,
      healingProfile: MONSTER_HEALING_PROFILE.SLOW,
      allowedTemperaments: [MONSTER_TEMPERAMENT.PATROL, MONSTER_TEMPERAMENT.STOIC],
    }),
    strength: 4,
    precision: 4,
    reaction: 3,
    nerves: 3,
    intelligence: 4,
    hp: 14,
    xpReward: 20,
    aggroRadius: 7,
    canOpenDoors: true,
    special: "Bleibt in mittlerer Distanz hartnäckig auf dem Ziel.",
  },

  {
    id: "pennywise",
    name: "Pennywise",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 7,
    behavior: "trickster",
    behaviorLabel: "Trickser",
    description: "Spielt mit Distanz, Verunsicherung und plötzlichen Ausbrüchen von Gewalt.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.COWARDLY,
      healingProfile: MONSTER_HEALING_PROFILE.LURKING,
      allowedTemperaments: [MONSTER_TEMPERAMENT.PATROL, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 6,
    precision: 5,
    reaction: 5,
    nerves: 5,
    intelligence: 7,
    hp: 21,
    xpReward: 38,
    aggroRadius: 7,
    canOpenDoors: true,
    special: "Erholt sich leicht, wenn er sich aus dem direkten Kampf löst.",
  },
  {
    id: "kanalclown",
    name: "Kanalclown",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 7,
    behavior: "trickster",
    behaviorLabel: "Trickser",
    description: "Ein grinsender Schrecken, der Unsicherheit fast ebenso gut einsetzt wie Gewalt.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.COWARDLY,
      healingProfile: MONSTER_HEALING_PROFILE.SLOW,
      allowedTemperaments: [MONSTER_TEMPERAMENT.RESTLESS, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 4,
    precision: 4,
    reaction: 4,
    nerves: 4,
    intelligence: 5,
    hp: 15,
    xpReward: 24,
    aggroRadius: 5,
    canOpenDoors: true,
    special: "Löst sich leichter aus dem direkten Schlagabtausch.",
  },
  {
    id: "gestaltlaeufer",
    name: "Gestaltläufer",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 7,
    behavior: "trickster",
    behaviorLabel: "Irrbild",
    description: "Nie ganz dort, wo man ihn erwartet, und nie so harmlos, wie er kurz wirkt.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.CAUTIOUS,
      healingProfile: MONSTER_HEALING_PROFILE.LURKING,
      allowedTemperaments: [MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 4,
    precision: 4,
    reaction: 5,
    nerves: 3,
    intelligence: 5,
    hp: 14,
    xpReward: 24,
    aggroRadius: 5,
    canOpenDoors: true,
    special: "Wechselt gern zwischen Annäherung und Rückzug.",
  },

  {
    id: "xenomorph",
    name: "Xenomorph",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 8,
    behavior: "stalker",
    behaviorLabel: "Raubtier",
    description: "Extrem schnell und in engen Gängen nahezu pausenlos auf Jagd.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.STEADY,
      allowedTemperaments: [MONSTER_TEMPERAMENT.RESTLESS],
    }),
    strength: 8,
    precision: 6,
    reaction: 7,
    nerves: 3,
    intelligence: 4,
    hp: 22,
    xpReward: 45,
    aggroRadius: 10,
    canOpenDoors: false,
    special: "Sehr weite Wahrnehmung und aggressive Jagd.",
  },
  {
    id: "critter",
    name: "Critter",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 8,
    behavior: "stalker",
    behaviorLabel: "Beißer",
    description: "Klein, schnell und mit viel zu vielen Zähnen für seine Größe.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.NONE,
      allowedTemperaments: [MONSTER_TEMPERAMENT.RESTLESS, MONSTER_TEMPERAMENT.ERRATIC],
    }),
    strength: 5,
    precision: 4,
    reaction: 5,
    nerves: 2,
    intelligence: 2,
    hp: 15,
    xpReward: 28,
    aggroRadius: 7,
    canOpenDoors: false,
    special: "Greift aggressiv an, sobald er Beute wittert.",
  },
  {
    id: "tunnelkriecher",
    name: "Tunnelkriecher",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 8,
    behavior: "stalker",
    behaviorLabel: "Raubtier",
    description: "Ein dürrer Jäger aus Schächten und Lüftungsgängen, schnell und unangenehm leise.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.NONE,
      allowedTemperaments: [MONSTER_TEMPERAMENT.RESTLESS, MONSTER_TEMPERAMENT.PATROL],
    }),
    strength: 5,
    precision: 4,
    reaction: 5,
    nerves: 2,
    intelligence: 2,
    hp: 16,
    xpReward: 28,
    aggroRadius: 8,
    canOpenDoors: false,
    special: "Hat eine weite Wahrnehmung in engen Bereichen.",
  },

  {
    id: "predator",
    name: "Predator",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 9,
    behavior: "hunter",
    behaviorLabel: "Jagdprofi",
    description: "Beobachtet erst, wählt dann den Moment und schlägt präzise zu.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.CAUTIOUS,
      healingProfile: MONSTER_HEALING_PROFILE.STEADY,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC, MONSTER_TEMPERAMENT.PATROL],
    }),
    strength: 9,
    precision: 7,
    reaction: 6,
    nerves: 5,
    intelligence: 7,
    hp: 24,
    xpReward: 52,
    aggroRadius: 9,
    offHand: "satellite-dish-guard",
    canOpenDoors: true,
    special: "Trägt einen Jagdschutz am Arm und jagt zielstrebig.",
  },
  {
    id: "trophaeenjaeger",
    name: "Trophäenjäger",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 9,
    behavior: "hunter",
    behaviorLabel: "Jagdprofi",
    description: "Ein disziplinierter Killer, der seine Ziele beobachtet wie Beute.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.CAUTIOUS,
      healingProfile: MONSTER_HEALING_PROFILE.SLOW,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC, MONSTER_TEMPERAMENT.PATROL],
    }),
    strength: 6,
    precision: 5,
    reaction: 4,
    nerves: 4,
    intelligence: 5,
    hp: 18,
    xpReward: 34,
    aggroRadius: 6,
    canOpenDoors: true,
    special: "Nähert sich kontrolliert und greift erst im richtigen Moment an.",
  },
  {
    id: "soeldner-tracker",
    name: "Söldner-Tracker",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 9,
    behavior: "hunter",
    behaviorLabel: "Tracker",
    description: "Weniger Show, mehr Professionalität – ein kalter Verfolger mit sicherer Hand.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.CAUTIOUS,
      healingProfile: MONSTER_HEALING_PROFILE.SLOW,
      allowedTemperaments: [MONSTER_TEMPERAMENT.PATROL],
    }),
    strength: 6,
    precision: 5,
    reaction: 4,
    nerves: 3,
    intelligence: 5,
    hp: 18,
    xpReward: 34,
    aggroRadius: 6,
    canOpenDoors: true,
    special: "Bleibt auf Distanz aufmerksam und drückt dann gezielt nach.",
  },

  {
    id: "vader",
    name: "Darth Vader",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 10,
    behavior: "hunter",
    behaviorLabel: "Dunkler Lord",
    description: "Ein spätes Elite-Monster mit eisiger Ruhe und überwältigender Präsenz.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.STEADY,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC],
    }),
    strength: 11,
    precision: 7,
    reaction: 5,
    nerves: 6,
    intelligence: 8,
    hp: 29,
    xpReward: 68,
    aggroRadius: 11,
    canOpenDoors: true,
    special: "Jagt kalt, direkt und mit eiserner Disziplin.",
  },
  {
    id: "dunkler-vollstrecker",
    name: "Dunkler Vollstrecker",
    grammar: createInflectableMonsterGrammar(MONSTER_GRAMMAR.GENERIC_MASCULINE, "dunkl", "Vollstrecker"),
    rank: 10,
    behavior: "hunter",
    behaviorLabel: "Vollstrecker",
    description: "Ein schwerer Elitegegner mit kalter Haltung und tödlicher Konsequenz.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.STEADY,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC, MONSTER_TEMPERAMENT.PATROL],
    }),
    strength: 8,
    precision: 5,
    reaction: 4,
    nerves: 5,
    intelligence: 6,
    hp: 21,
    xpReward: 44,
    aggroRadius: 8,
    canOpenDoors: true,
    special: "Setzt mit disziplinierter Härte nach.",
  },
  {
    id: "sternen-inquisitor",
    name: "Sternen-Inquisitor",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 10,
    behavior: "hunter",
    behaviorLabel: "Inquisitor",
    description: "Ruhig, kontrolliert und mit jener Autorität, die jeden Raum sofort verändert.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.ROAMING,
      retreatProfile: MONSTER_RETREAT_PROFILE.CAUTIOUS,
      healingProfile: MONSTER_HEALING_PROFILE.STEADY,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC, MONSTER_TEMPERAMENT.PATROL],
    }),
    strength: 7,
    precision: 6,
    reaction: 4,
    nerves: 5,
    intelligence: 6,
    hp: 20,
    xpReward: 44,
    aggroRadius: 8,
    canOpenDoors: true,
    special: "Jagt ohne Hast, aber ohne jeden Zweifel.",
  },

  {
    id: "terminator",
    name: "Terminator",
    grammar: { ...MONSTER_GRAMMAR.NAMED_MASCULINE },
    rank: 11,
    behavior: "hunter",
    behaviorLabel: "Unaufhaltsam",
    description: "Kalte Maschine, die sich nicht abschütteln lässt und jeden Fehler bestraft.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.STEADY,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC],
    }),
    strength: 12,
    precision: 6,
    reaction: 4,
    nerves: 6,
    intelligence: 7,
    hp: 34,
    xpReward: 84,
    aggroRadius: 12,
    canOpenDoors: true,
    special: "Kann dir als einziger Gegner über Treppen in andere Studios folgen.",
    canChangeFloors: true,
  },
  {
    id: "killerdrohne",
    name: "Killerdrohne",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_FEMININE },
    rank: 11,
    behavior: "hunter",
    behaviorLabel: "Maschine",
    description: "Präzise, kalt und frei von jedem Zögern – eher Protokoll als Persönlichkeit.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.NONE,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC, MONSTER_TEMPERAMENT.PATROL],
    }),
    strength: 8,
    precision: 5,
    reaction: 4,
    nerves: 5,
    intelligence: 5,
    hp: 24,
    xpReward: 56,
    aggroRadius: 9,
    canOpenDoors: true,
    special: "Verfolgt Ziele zuverlässig und ohne Ermüdung.",
  },
  {
    id: "cyborg-vollstrecker",
    name: "Cyborg-Vollstrecker",
    grammar: { ...MONSTER_GRAMMAR.GENERIC_MASCULINE },
    rank: 11,
    behavior: "juggernaut",
    behaviorLabel: "Unaufhaltsam",
    description: "Mehr Metall als Mensch und nur einem Auftrag verpflichtet.",
    ...createMonsterAiProfile({
      mobility: MONSTER_MOBILITY.RELENTLESS,
      retreatProfile: MONSTER_RETREAT_PROFILE.NONE,
      healingProfile: MONSTER_HEALING_PROFILE.STEADY,
      allowedTemperaments: [MONSTER_TEMPERAMENT.STOIC],
    }),
    strength: 9,
    precision: 4,
    reaction: 3,
    nerves: 5,
    intelligence: 5,
    hp: 25,
    xpReward: 56,
    aggroRadius: 8,
    canOpenDoors: true,
    special: "Rückt stoisch vor und lässt sich kaum abschütteln.",
  },
].map(applyLegacySpecialPoolConfig);

MONSTER_CATALOG.push(...PHASE_ONE_STANDARD_MONSTERS);

const MONSTER_BASE_SPEED_BY_ID = Object.freeze({
  "bates": 110,
  "motel-shlurfer": 105,
  "kellerkriecher": 105,
  "ghostface": 90,
  "maskierter-nachahmer": 95,
  "videotheken-stalker": 95,
  "chucky": 95,
  "besessene-puppe": 105,
  "gremlin": 90,
  "myers": 115,
  "stummer-maskentraeger": 115,
  "friedhofsschlurfer": 120,
  "jason": 115,
  "camp-schlaechter": 120,
  "mutierter-hinterwaeldler": 120,
  "freddy": 90,
  "traumwandler": 95,
  "kesselraum-peiniger": 95,
  "pennywise": 85,
  "kanalclown": 90,
  "gestaltlaeufer": 90,
  "xenomorph": 85,
  "critter": 90,
  "tunnelkriecher": 95,
  "predator": 85,
  "trophaeenjaeger": 95,
  "soeldner-tracker": 95,
  "vader": 90,
  "dunkler-vollstrecker": 90,
  "sternen-inquisitor": 95,
  "terminator": 90,
  "killerdrohne": 90,
  "cyborg-vollstrecker": 115,
  "fantasy-goblin-pluenderer": 100,
  "fantasy-skelettwaechter": 115,
  "fantasy-kult-akolyth": 90,
  "fantasy-riesenspinne": 95,
  "fantasy-ork-marodeur": 95,
  "fantasy-verzauberte-ruestung": 110,
  "fantasy-nekromant": 95,
  "fantasy-troll-brute": 125,
  "fantasy-schattenlaeufer": 85,
  "fantasy-dunkelritter": 115,
  "action-wachmann": 110,
  "action-schlaeger": 120,
  "action-messerfanatiker": 90,
  "action-soeldner": 95,
  "action-sprengstoff-experte": 95,
  "action-ex-cop-veteran": 95,
  "action-elite-soldat": 90,
  "action-berserker-gangmitglied": 120,
  "action-auftragskiller": 85,
  "action-scharfschuetze": 95,
  "western-ranch-hand-schuetze": 105,
  "western-bandit": 100,
  "western-saloon-schlaeger": 125,
  "western-messerwerfer": 90,
  "western-wuestenpluenderer": 95,
  "western-revolverheld": 95,
  "western-prediger-fanatiker": 95,
  "western-gesetzeshueter": 90,
  "western-galgenvogt": 125,
  "western-kopfgeldjaeger": 85,
  "slasher-kellerkreatur": 115,
  "slasher-kultist": 90,
  "slasher-wahnsinniger-hausmeister": 105,
  "slasher-puppenmoerder": 90,
  "slasher-verfluchter-arzt": 95,
  "slasher-rasender-moerder": 120,
  "slasher-spukhafte-braut": 90,
  "slasher-fleischkoloss": 125,
  "slasher-unsichtbarer-verfolger": 85,
  "slasher-maskierter-killer": 85,
  "noir-syndikatsbuchhalter": 115,
  "noir-informanten-schieber": 90,
  "noir-gangster-schuetze": 100,
  "noir-messerstecher": 90,
  "noir-geldeintreiber": 95,
  "noir-fluchtfahrer": 100,
  "noir-korruptions-cop": 90,
  "noir-club-bodyguard": 125,
  "noir-vollstrecker-des-syndikats": 115,
  "noir-auftragsmoerder": 85,
  "adventure-grabraeuber": 100,
  "adventure-tempelwaechter": 115,
  "adventure-schlangenpriester": 95,
  "adventure-peitschen-soeldner": 95,
  "adventure-mumienkrieger": 100,
  "adventure-fanatischer-expeditionsfuehrer": 90,
  "adventure-dschungelbestie": 90,
  "adventure-schatzsucher-veteran": 90,
  "adventure-stein-golem": 125,
  "adventure-verfluchter-hueter": 85,
  "space-opera-wartungsautomat": 115,
  "space-opera-sicherheitsdrohne": 100,
  "space-opera-schrottsammler-raider": 100,
  "space-opera-raumstations-marine": 95,
  "space-opera-fehlgesteuerte-ki-einheit": 90,
  "space-opera-android-waechter": 95,
  "space-opera-psioniker": 95,
  "space-opera-sternenreich-vollstrecker": 90,
  "space-opera-panzer-exosuit": 125,
  "space-opera-tarnjaeger": 85,
  "creature-feature-tunnelkriecher": 100,
  "creature-feature-schleimkreatur": 115,
  "creature-feature-bio-experiment": 90,
  "creature-feature-parasitenwirt": 95,
  "creature-feature-insektoider-spalter": 95,
  "creature-feature-brutschwarm-traeger": 90,
  "creature-feature-amphibischer-schrecken": 90,
  "creature-feature-mutierter-brute": 120,
  "creature-feature-schachtjaeger": 85,
  "creature-feature-laborkoloss": 125,
  "romcom-nervoeser-caterer": 95,
  "romcom-chaotischer-trauzeuge": 100,
  "romcom-wedding-crasher": 100,
  "romcom-paparazzo": 95,
  "romcom-brautjungfern-tyrannin": 95,
  "romcom-eifersuechtiger-ex": 95,
  "romcom-starallueren-diva-wache": 90,
  "romcom-uebereifriger-tuersteher": 125,
  "romcom-toxischer-loverboy": 90,
  "romcom-stalkender-fan": 85,
  "social-drama-klinikordner": 110,
  "social-drama-fanatischer-hausmeister": 110,
  "social-drama-schuldeneintreiber": 95,
  "social-drama-gewalttaetiger-ex-partner": 95,
  "social-drama-security-chef": 95,
  "social-drama-strassen-gang-anfuehrer": 95,
  "social-drama-korrupter-vermieter-schlaeger": 125,
  "social-drama-heimleiterin-im-ausnahmezustand": 95,
  "social-drama-zermuerbter-veteran": 85,
  "social-drama-streikbrecher": 115,
});

// The speed pass is curated in content, even when a monster intentionally stays at 100.
for (const monster of MONSTER_CATALOG) {
  monster.baseSpeed = MONSTER_BASE_SPEED_BY_ID[monster.id] ?? 100;
}

