export const DISPLAY_CASE_DEFS = {
  "jason-mask": {
    id: "jason-mask",
    archetype: "slasher",
    name: "Hockeymaske",
    source: "Friday the 13th",
    sourceLabelDe: "Freitag der 13.",
  },
  "bates-knife": {
    id: "bates-knife",
    archetype: "slasher",
    name: "Kuechenmesser",
    source: "Psycho",
    sourceLabelDe: "Psycho",
  },
  "freddy-glove": {
    id: "freddy-glove",
    archetype: "slasher",
    name: "Klingenhandschuh",
    source: "A Nightmare on Elm Street",
    sourceLabelDe: "Nightmare",
  },
  "myers-mask": {
    id: "myers-mask",
    archetype: "slasher",
    name: "Weisse Maske",
    source: "Halloween",
    sourceLabelDe: "Halloween",
  },
  "ghostface-mask": {
    id: "ghostface-mask",
    archetype: "slasher",
    name: "Schrei-Maske",
    source: "Scream",
    sourceLabelDe: "Scream",
  },
  "chucky-doll": {
    id: "chucky-doll",
    archetype: "slasher",
    name: "Unheimliche Puppe",
    source: "Child's Play",
    sourceLabelDe: "Chucky - Die Moerderpuppe",
  },
  chainsaw: {
    id: "chainsaw",
    archetype: "slasher",
    name: "Kettensaege",
    source: "The Texas Chain Saw Massacre",
    sourceLabelDe: "Blutgericht in Texas",
  },
  "cursed-vhs": {
    id: "cursed-vhs",
    archetype: "slasher",
    name: "Verfluchte VHS",
    source: "The Ring",
    sourceLabelDe: "Ring",
  },
  "red-balloon": {
    id: "red-balloon",
    archetype: "slasher",
    name: "Roter Ballon",
    source: "It",
    sourceLabelDe: "Es",
  },
  "shining-axe": {
    id: "shining-axe",
    archetype: "slasher",
    name: "Axt",
    source: "The Shining",
    sourceLabelDe: "Shining",
  },
  "music-box": {
    id: "music-box",
    archetype: "slasher",
    name: "Spieluhr",
    source: "Annabelle",
    sourceLabelDe: "Annabelle",
  },

  "indy-hat-whip": {
    id: "indy-hat-whip",
    archetype: "adventure",
    name: "Hut und Peitsche",
    source: "Indiana Jones",
    sourceLabelDe: "Indiana Jones",
  },
  "golden-idol": {
    id: "golden-idol",
    archetype: "adventure",
    name: "Goldenes Idol",
    source: "Raiders of the Lost Ark",
    sourceLabelDe: "Jaeger des verlorenen Schatzes",
  },
  "fedora-whip": {
    id: "fedora-whip",
    archetype: "adventure",
    name: "Reisehut und Peitsche",
    source: "Indiana Jones",
    sourceLabelDe: "Indiana Jones",
  },
  "crystal-skull": {
    id: "crystal-skull",
    archetype: "adventure",
    name: "Kristallschaedel",
    source: "Indiana Jones and the Kingdom of the Crystal Skull",
    sourceLabelDe: "Indiana Jones und das Koenigreich des Kristallschaedels",
  },
  "zorro-mask": {
    id: "zorro-mask",
    archetype: "adventure",
    name: "Duellmaske",
    source: "The Mask of Zorro",
    sourceLabelDe: "Die Maske des Zorro",
  },

  "lightsaber-hilt": {
    id: "lightsaber-hilt",
    archetype: "space_opera",
    name: "Lichtschwertgriff",
    source: "Star Wars",
    sourceLabelDe: "Star Wars",
  },
  "flux-capacitor": {
    id: "flux-capacitor",
    archetype: "space_opera",
    name: "Fluxkompensator",
    source: "Back to the Future",
    sourceLabelDe: "Zurueck in die Zukunft",
  },
  hoverboard: {
    id: "hoverboard",
    archetype: "space_opera",
    name: "Hoverboard",
    source: "Back to the Future Part II",
    sourceLabelDe: "Zurueck in die Zukunft II",
  },
  "cyber-hand": {
    id: "cyber-hand",
    archetype: "space_opera",
    name: "Kybernetische Hand",
    source: "The Terminator",
    sourceLabelDe: "Terminator",
  },

  "badge-holster": {
    id: "badge-holster",
    archetype: "noir",
    name: "Marke und Schulterholster",
    source: "Chinatown",
    sourceLabelDe: "Chinatown",
  },
  "black-chess-set": {
    id: "black-chess-set",
    archetype: "noir",
    name: "Schwarzes Schachspiel",
    source: "The Seventh Seal",
    sourceLabelDe: "Das siebente Siegel",
  },
  "hotel-key-board": {
    id: "hotel-key-board",
    archetype: "noir",
    name: "Schluesselbrett",
    source: "Barton Fink",
    sourceLabelDe: "Barton Fink",
  },
  "case-files": {
    id: "case-files",
    archetype: "noir",
    name: "Fallakten",
    source: "L.A. Confidential",
    sourceLabelDe: "L.A. Confidential",
  },

  "heart-jewel-box": {
    id: "heart-jewel-box",
    archetype: "romcom",
    name: "Herz-Schatulle",
    source: "Titanic",
    sourceLabelDe: "Titanic",
  },
  "rose-under-glass": {
    id: "rose-under-glass",
    archetype: "romcom",
    name: "Rose unter Glas",
    source: "Beauty and the Beast",
    sourceLabelDe: "Die Schoene und das Biest",
  },
  "cafe-menu-board": {
    id: "cafe-menu-board",
    archetype: "romcom",
    name: "Cafe-Menueboard",
    source: "You've Got Mail",
    sourceLabelDe: "e-m@il fuer Dich",
  },
  "engagement-ring-box": {
    id: "engagement-ring-box",
    archetype: "romcom",
    name: "Ringschaechtelchen",
    source: "When Harry Met Sally",
    sourceLabelDe: "Harry und Sally",
  },
  "diner-neon-jukebox": {
    id: "diner-neon-jukebox",
    archetype: "romcom",
    name: "Neon-Jukebox",
    source: "American Graffiti",
    sourceLabelDe: "American Graffiti",
  },
  "jukebox-module": {
    id: "jukebox-module",
    archetype: "romcom",
    name: "Jukebox-Modul",
    source: "Grease",
    sourceLabelDe: "Grease",
  },

  lunchbox: {
    id: "lunchbox",
    archetype: "social_drama",
    name: "Brotdose",
    source: "Kramer vs. Kramer",
    sourceLabelDe: "Kramer gegen Kramer",
  },
  "work-boots": {
    id: "work-boots",
    archetype: "social_drama",
    name: "Arbeitsstiefel",
    source: "Nomadland",
    sourceLabelDe: "Nomadland",
  },
  "eviction-notice": {
    id: "eviction-notice",
    archetype: "social_drama",
    name: "Raeumungsbescheid",
    source: "Parasite",
    sourceLabelDe: "Parasite",
  },
  "bus-pass-wallet": {
    id: "bus-pass-wallet",
    archetype: "social_drama",
    name: "Portemonnaie mit Fahrkarte",
    source: "The Pursuit of Happyness",
    sourceLabelDe: "Das Streben nach Glueck",
  },

  "terminator-jacket-glasses": {
    id: "terminator-jacket-glasses",
    archetype: "action",
    name: "Jacke und Sonnenbrille",
    source: "The Terminator",
    sourceLabelDe: "Terminator",
  },
  "motion-tracker": {
    id: "motion-tracker",
    archetype: "action",
    name: "Bewegungsscanner",
    source: "Aliens",
    sourceLabelDe: "Aliens - Die Rueckkehr",
  },
  "ghostbusters-radios": {
    id: "ghostbusters-radios",
    archetype: "action",
    name: "Funkgeraete",
    source: "Ghostbusters",
    sourceLabelDe: "Ghostbusters - Die Geisterjaeger",
  },
  "tactical-vest": {
    id: "tactical-vest",
    archetype: "action",
    name: "Schutzweste",
    source: "Die Hard",
    sourceLabelDe: "Stirb langsam",
  },

  "cowboy-hat-spurs": {
    id: "cowboy-hat-spurs",
    archetype: "western",
    name: "Cowboyhut und Sporen",
    source: "The Good, the Bad and the Ugly",
    sourceLabelDe: "Zwei glorreiche Halunken",
  },
  "sheriff-star": {
    id: "sheriff-star",
    archetype: "western",
    name: "Sheriffstern",
    source: "High Noon",
    sourceLabelDe: "Zwoelf Uhr mittags",
  },
  "wanted-poster": {
    id: "wanted-poster",
    archetype: "western",
    name: "Steckbrief",
    source: "For a Few Dollars More",
    sourceLabelDe: "Fuer ein paar Dollar mehr",
  },
  "silver-buckle": {
    id: "silver-buckle",
    archetype: "western",
    name: "Silberne Guertelschliesse",
    source: "Tombstone",
    sourceLabelDe: "Tombstone",
  },

  necronomicon: {
    id: "necronomicon",
    archetype: "fantasy",
    name: "Verbotenes Buch",
    source: "Evil Dead",
    sourceLabelDe: "Tanz der Teufel",
  },
  "puzzle-box": {
    id: "puzzle-box",
    archetype: "fantasy",
    name: "Raetselschatulle",
    source: "Hellraiser",
    sourceLabelDe: "Hellraiser",
  },
  "labyrinth-artifact": {
    id: "labyrinth-artifact",
    archetype: "fantasy",
    name: "Labyrinth-Artefakt",
    source: "Labyrinth",
    sourceLabelDe: "Die Reise ins Labyrinth",
  },
  "enchanted-mirror": {
    id: "enchanted-mirror",
    archetype: "fantasy",
    name: "Verzauberter Spiegel",
    source: "Snow White",
    sourceLabelDe: "Schneewittchen",
  },

  "facehugger-tank": {
    id: "facehugger-tank",
    archetype: "creature_feature",
    name: "Tank mit Kreatur",
    source: "Alien",
    sourceLabelDe: "Alien - Das unheimliche Wesen aus einer fremden Welt",
  },
  "amber-mosquito": {
    id: "amber-mosquito",
    archetype: "creature_feature",
    name: "Bernstein mit Muecke",
    source: "Jurassic Park",
    sourceLabelDe: "Jurassic Park",
  },
  "ghost-trap": {
    id: "ghost-trap",
    archetype: "creature_feature",
    name: "Geisterfalle",
    source: "Ghostbusters",
    sourceLabelDe: "Ghostbusters - Die Geisterjaeger",
  },
  "pke-meter": {
    id: "pke-meter",
    archetype: "creature_feature",
    name: "PKE-Meter",
    source: "Ghostbusters",
    sourceLabelDe: "Ghostbusters - Die Geisterjaeger",
  },

  "film-clapper": {
    id: "film-clapper",
    archetype: "global",
    name: "Filmklappe",
    source: null,
    sourceLabelDe: "Allgemeine Filmrequisite",
  },
  "film-award": {
    id: "film-award",
    archetype: "global",
    name: "Filmpreis",
    source: null,
    sourceLabelDe: "Allgemeine Filmrequisite",
  },
};

const DISPLAY_CASE_DESCRIPTIONS = {
  "jason-mask": "Eine stumpf gewordene Eishockeymaske hinter Glas. Selbst still wirkt sie bedrohlich.",
  "bates-knife": "Schlichtes Stahlmesser aus einem Motel-Albtraum, sauber ausgeleuchtet in der Vitrine.",
  "freddy-glove": "Metall trifft Strickstoff und boese Erinnerungen. Die Klingen funkeln im Halbdunkel.",
  "myers-mask": "Fast ausdruckslos und genau deshalb unheimlich. Hinter dem Glas noch stiller als sonst.",
  "ghostface-mask": "Die langgezogene Fratze haengt in der Vitrine wie ein eingefrorener Schrei.",
  "chucky-doll": "Zu klein fuer den Raum und trotzdem sofort der Mittelpunkt. Jemand hat sie aufrecht gesetzt.",
  "puzzle-box": "Ein geometrisches Raetselobjekt mit falschem Goldglanz und einer unangenehmen Aura.",
  chainsaw: "Verrostete Zaehne, schweres Gehaeuse, stumpfer Schrecken. Gut, dass Glas dazwischen ist.",
  necronomicon: "Leder, Naehte und etwas, das nicht wie Tinte aussieht. Die Seiten liegen halb offen.",
  "cursed-vhs": "Unspektakulaer als Objekt, aber niemand bleibt lange davor stehen.",
  "indy-hat-whip": "Abenteuer in Reinform: Leder, Staub und der Eindruck, dass die Vitrine zu klein ist.",
  "golden-idol": "Kompakt, schwer wirkend und mit genau dem Glanz, der schlechte Entscheidungen ausloest.",
  "fedora-whip": "Sorgsam praesentiert wie ein Museumsstueck aus einer gluecklicheren Karriere.",
  "lightsaber-hilt": "Nur der Griff und doch sofort erkennbar. Die Vitrine spiegelt sein kaltes Metall.",
  "zorro-mask": "Ein Gesicht aus Stoff und Stil, stolz und leicht theatralisch. Fast zu elegant fuer diesen Ort.",
  "flux-capacitor": "Kabel, Lichtstreben und pure Filmwissenschaft. Hinter Glas wirkt es noch absurder.",
  hoverboard: "Schraeg aufgebockt wie ein Sportgeraet aus einer Zukunft, die nie eingetroffen ist.",
  "ghostbusters-radios": "Leicht abgenutzte Funkgeraete, sauber ausgerichtet, als waeren sie noch im Einsatz.",
  "ghost-trap": "Eine schwere Kiste voller Versprechen und Risiken. Zum Glueck verriegelt.",
  "pke-meter": "Ein seltsam technisches Geraet mit Antennen, Griff und sofortiger Wiedererkennbarkeit.",
  "red-balloon": "In einer Vitrine eigentlich unsinnig. Genau deshalb wirkt er noch falscher.",
  "hotel-key-board": "Verwittertes Schluesselbrett, leer und trotzdem voller Geschichten von Leuten, die nicht auscheckten.",
  "shining-axe": "Wie eine Trophaee ausgestellt. Man merkt dem Holz die Gewalt noch an.",
  "crystal-skull": "Zu glatt, zu klar, zu perfekt. Das Ding scheint jeden Winkel des Raums zu sehen.",
  "heart-jewel-box": "Tiefblau und fehl am Platz zwischen all den Fundstuecken. Gerade deshalb bleibt man kurz stehen.",
  "rose-under-glass": "Fast zu maerchenhaft fuer diesen Ort. Das Glas wirkt klarer als die Luft drumherum.",
  "film-clapper": "Volle Produktionskritzeleien, halbe Brandspuren. Sie fuehlt sich hier beinahe zuhause an.",
  "film-award": "Eine Oscar-aehnliche Statue, stolz beleuchtet und etwas zu sauber fuer den Rest des Raums.",
  "terminator-jacket-glasses": "Die Pose verkauft Coolness, aber die Vitrine verraet eher eine Warnung.",
  "cyber-hand": "Metallische Finger unter klarem Kunstharz. Ein eingefrorener Blick in eine schlechte Zukunft.",
  "motion-tracker": "Militaerisches Plastik und ein Display, das man instinktiv nicht blinken sehen will.",
  "facehugger-tank": "Das Glas ist dick. Hoffentlich dick genug.",
  "amber-mosquito": "Klein, unscheinbar und mit unverhaeltnismaessig grosser Tragweite fuer die Popkultur.",
  "labyrinth-artifact": "Ein verschachtelter Wuerfel aus Ornamenten und Spiegelungen. Mehr Versprechen als Erklaerung.",
  "badge-holster": "Dienstmarke und Lederholster, arrangiert wie ein letzter Rest harter Grossstadtfilme.",
  "music-box": "Zu filigran fuer diesen Raum, und gerade deshalb ein wenig beunruhigend.",
  "video-camera": "Abgenutzt, kantig und so praesentiert, als waere die letzte Aufnahme noch darin gefangen.",
  "black-chess-set": "Matt schwarzer Stein, exakt aufgestellt. Ein stilles Spiel mit schwerem Unterton.",
  "cowboy-hat-spurs": "Staubige Romantik aus einem anderen Genre, sorgsam und fast nostalgisch praesentiert.",
  "diner-neon-jukebox": "Zerkratztes Chrom, rote Scheibe, ein Hauch Diner und schlechte Entscheidungen.",
};

function buildDisplayCaseDescription(def) {
  return DISPLAY_CASE_DESCRIPTIONS[def.id]
    ?? `${def.name} sorgsam unter Glas praesentiert.`;
}

const ACTIVE_DISPLAY_CASE_IDS = new Set([
  "jason-mask",
  "bates-knife",
  "freddy-glove",
  "myers-mask",
  "ghostface-mask",
  "chucky-doll",
  "chainsaw",
  "cursed-vhs",
  "red-balloon",
  "shining-axe",
  "music-box",
  "indy-hat-whip",
  "golden-idol",
  "fedora-whip",
  "crystal-skull",
  "zorro-mask",
  "lightsaber-hilt",
  "flux-capacitor",
  "hoverboard",
  "cyber-hand",
  "badge-holster",
  "black-chess-set",
  "hotel-key-board",
  "case-files",
  "heart-jewel-box",
  "rose-under-glass",
  "cafe-menu-board",
  "engagement-ring-box",
  "diner-neon-jukebox",
  "jukebox-module",
  "lunchbox",
  "work-boots",
  "eviction-notice",
  "bus-pass-wallet",
  "terminator-jacket-glasses",
  "motion-tracker",
  "ghostbusters-radios",
  "tactical-vest",
  "cowboy-hat-spurs",
  "sheriff-star",
  "wanted-poster",
  "silver-buckle",
  "necronomicon",
  "puzzle-box",
  "labyrinth-artifact",
  "enchanted-mirror",
  "facehugger-tank",
  "amber-mosquito",
  "ghost-trap",
  "pke-meter",
  "film-clapper",
  "film-award",
  "video-camera",
]);

export const PROP_CATALOG = Object.values(DISPLAY_CASE_DEFS)
  .filter((def) => ACTIVE_DISPLAY_CASE_IDS.has(def.id))
  .map((def) => ({
  id: def.id,
  ambienceId: def.id,
  archetype: def.archetype,
  name: def.name,
  source: def.sourceLabelDe ?? def.source ?? "Unbekannte Quelle",
  description: buildDisplayCaseDescription(def),
  }));
