export const PROP_CATALOG = [
  {
    id: "jason-hockey-mask",
    ambienceId: "jason-mask",
    name: "Hockeymaske von Jason",
    source: "Freitag der 13.",
    description: "Eine stumpf gewordene Eishockeymaske hinter Glas. Selbst still wirkt sie bedrohlich.",
  },
  {
    id: "bates-kitchen-knife",
    ambienceId: "bates-knife",
    name: "Küchenmesser von Norman Bates",
    source: "Psycho",
    description: "Schlichtes Stahlmesser aus einem Motel-Albtraum, sauber ausgeleuchtet in der Vitrine.",
  },
  {
    id: "freddy-claw-glove",
    ambienceId: "freddy-glove",
    name: "Gestreifter Handschuh mit Klingen",
    source: "A Nightmare on Elm Street",
    description: "Metall trifft Strickstoff und böse Erinnerungen. Die Klingen funkeln im Halbdunkel.",
  },
  {
    id: "myers-white-mask",
    ambienceId: "myers-mask",
    name: "Weiße Maske von Michael Myers",
    source: "Halloween",
    description: "Fast ausdruckslos und genau deshalb unheimlich. Hinter dem Glas noch stiller als sonst.",
  },
  {
    id: "ghostface-mask",
    ambienceId: "ghostface-mask",
    name: "Ghostface-Maske",
    source: "Scream",
    description: "Die langgezogene Fratze hängt in der Vitrine wie ein eingefrorener Schrei.",
  },
  {
    id: "chucky-doll",
    ambienceId: "chucky-doll",
    name: "Chucky-Puppe",
    source: "Child's Play",
    description: "Zu klein für den Raum und trotzdem sofort der Mittelpunkt. Jemand hat sie aufrecht gesetzt.",
  },
  {
    id: "lament-configuration",
    ambienceId: "puzzle-box",
    name: "Puzzle-Box",
    source: "Hellraiser",
    description: "Ein geometrisches Rätselobjekt mit falschem Goldglanz und einer unangenehmen Aura.",
  },
  {
    id: "leatherface-chainsaw",
    ambienceId: "chainsaw",
    name: "Kettensäge von Leatherface",
    source: "The Texas Chain Saw Massacre",
    description: "Verrostete Zähne, schweres Gehäuse, stumpfer Schrecken. Gut, dass Glas dazwischen ist.",
  },
  {
    id: "necronomicon",
    ambienceId: "necronomicon",
    name: "Necronomicon-Buch",
    source: "Evil Dead",
    description: "Leder, Nähte und etwas, das nicht wie Tinte aussieht. Die Seiten liegen halb offen.",
  },
  {
    id: "ring-vhs",
    ambienceId: "cursed-vhs",
    name: "VHS-Kassette aus dem Brunnenfluch",
    source: "Ring / The Ring",
    description: "Unspektakulär als Objekt, aber niemand bleibt lange davor stehen.",
  },
  {
    id: "indy-hat-whip",
    ambienceId: "indy-hat-whip",
    name: "Trilby-Hut und Peitsche",
    source: "Indiana Jones",
    description: "Abenteuer in Reinform: Leder, Staub und der Eindruck, dass die Vitrine zu klein ist.",
  },
  {
    id: "golden-idol",
    ambienceId: "golden-idol",
    name: "Goldene Götzenfigur",
    source: "Raiders of the Lost Ark",
    description: "Kompakt, schwer wirkend und mit genau dem Glanz, der schlechte Entscheidungen auslöst.",
  },
  {
    id: "fedora-stand",
    ambienceId: "fedora-whip",
    name: "Peitsche und Fedora auf einem Ständer",
    source: "Indiana-Jones-Anspielung",
    description: "Sorgsam präsentiert wie ein Museumsstück aus einer gluecklicheren Karriere.",
  },
  {
    id: "lightsaber-hilt",
    ambienceId: "lightsaber-hilt",
    name: "Lichtschwertgriff in Glas",
    source: "Star Wars",
    description: "Nur der Griff und doch sofort erkennbar. Die Vitrine spiegelt sein kaltes Metall.",
  },
  {
    id: "zorro-idol-mask",
    ambienceId: "zorro-mask",
    name: "Goldene Idol-Maske",
    source: "The Mask of Zorro",
    description: "Ein Gesicht aus Gold, stolz und leicht theatralisch. Fast zu edel für diesen Ort.",
  },
  {
    id: "flux-model",
    ambienceId: "flux-capacitor",
    name: "Flux-Kondensator-Modell",
    source: "Back to the Future",
    description: "Kabel, Lichtstreben und pure Filmwissenschaft. Hinter Glas wirkt es noch absurder.",
  },
  {
    id: "hoverboard",
    ambienceId: "hoverboard",
    name: "Hoverboard",
    source: "Back to the Future Part II",
    description: "Schräg aufgebockt wie ein Sportgerät aus einer Zukunft, die nie eingetroffen ist.",
  },
  {
    id: "ghostbusters-walkies",
    ambienceId: "ghostbusters-radios",
    name: "Walkie-Talkie-Set mit Geisterjäger-Logo",
    source: "Ghostbusters",
    description: "Leicht abgenutzte Funkgeräte, sauber ausgerichtet, als wären sie noch im Einsatz.",
  },
  {
    id: "ghost-trap",
    ambienceId: "ghost-trap",
    name: "Geisterfalle",
    source: "Ghostbusters",
    description: "Eine schwere Kiste voller Versprechen und Risiken. Zum Glück verriegelt.",
  },
  {
    id: "pke-meter",
    ambienceId: "pke-meter",
    name: "PKE-Meter",
    source: "Ghostbusters",
    description: "Ein seltsam technisches Gerät mit Antennen, Griff und sofortiger Wiedererkennbarkeit.",
  },
  {
    id: "red-balloon",
    ambienceId: "red-balloon",
    name: "Roter Luftballon",
    source: "Es",
    description: "In einer Vitrine eigentlich unsinnig. Genau deshalb wirkt er noch falscher.",
  },
  {
    id: "shining-key-board",
    ambienceId: "hotel-key-board",
    name: "Hotel-Zimmerschlüsselbrett",
    source: "The Shining",
    description: "Verwittertes Schlüsselbrett, leer und trotzdem voller Geschichten von Leuten, die nicht auscheckten.",
  },
  {
    id: "shining-axe",
    ambienceId: "shining-axe",
    name: "Axt im Holzsockel",
    source: "The Shining",
    description: "Wie eine Trophäe ausgestellt. Man merkt dem Holz die Gewalt noch an.",
  },
  {
    id: "crystal-skull",
    ambienceId: "crystal-skull",
    name: "Kristallschaedel",
    source: "Indiana Jones and the Kingdom of the Crystal Skull",
    description: "Zu glatt, zu klar, zu perfekt. Das Ding scheint jeden Winkel des Raums zu sehen.",
  },
  {
    id: "titanic-heart",
    ambienceId: "heart-jewel-box",
    name: "Herz in einer Schmuckschatulle",
    source: "Titanic",
    description: "Tiefblau und fehl am Platz zwischen all dem Horror. Gerade deshalb bleibt man kurz stehen.",
  },
  {
    id: "glass-bell-rose",
    ambienceId: "rose-under-glass",
    name: "Rose in einer Glasglocke",
    source: "Beauty and the Beast",
    description: "Fast zu märchenhaft für den Studiokomplex. Das Glas wirkt klarer als die Luft drumherum.",
  },
  {
    id: "film-clapper",
    ambienceId: "film-clapper",
    name: "Filmklappe mit eingebrannten Notizen",
    source: "Filmset",
    description: "Volle Produktionskritzeleien, halbe Brandspuren. Sie fühlt sich hier beinahe zuhause an.",
  },
  {
    id: "hollywood-trophy",
    ambienceId: "film-award",
    name: "Goldene Trophäe",
    source: "Hollywood-Motiv",
    description: "Eine Oscar-ähnliche Statue, stolz beleuchtet und etwas zu sauber für den Rest des Studiokomplexes.",
  },
  {
    id: "terminator-bust",
    ambienceId: "terminator-jacket-glasses",
    name: "Sonnenbrille und Lederjacke auf Büste",
    source: "Terminator",
    description: "Die Pose verkauft Coolness, aber die Vitrine verrät eher eine Warnung.",
  },
  {
    id: "cyber-hand",
    ambienceId: "cyber-hand",
    name: "Cyberhand im Acrylblock",
    source: "Terminator 2",
    description: "Metallische Finger unter klarem Kunstharz. Ein eingefrorener Blick in eine schlechte Zukunft.",
  },
  {
    id: "motion-tracker",
    ambienceId: "motion-tracker",
    name: "Bewegungsmelder",
    source: "Aliens",
    description: "Militärisches Plastik und ein Display, das man instinktiv nicht blinken sehen will.",
  },
  {
    id: "facehugger-jar",
    ambienceId: "facehugger-tank",
    name: "Facehugger im Glasbehälter",
    source: "Alien",
    description: "Das Glas ist dick. Hoffentlich dick genug.",
  },
  {
    id: "amber-mosquito",
    ambienceId: "amber-mosquito",
    name: "Bernstein mit Mücke",
    source: "Jurassic Park",
    description: "Klein, unscheinbar und mit unverhältnismaessig großer Tragweite für die Popkultur.",
  },
  {
    id: "fantasy-labyrinth-artifact",
    ambienceId: "labyrinth-artifact",
    name: "Labyrinth-Artefakt",
    source: "Fantasy-Film-Anmutung",
    description: "Ein verschachtelter Würfel aus Ornamenten und Spiegelungen. Mehr Versprechen als Erklärung.",
  },
  {
    id: "badge-and-holster",
    ambienceId: "badge-holster",
    name: "Police-Badge und Revolver-Holster",
    source: "Cop-Kino-Anklang",
    description: "Dienstmarke und Lederholster, arrangiert wie ein letzter Rest harter Großstadtfilme.",
  },
  {
    id: "ballerina-music-box",
    ambienceId: "music-box",
    name: "Spieluhr mit Ballerina",
    source: "Horror- und Mystery-Filmklischee",
    description: "Zu filigran für diesen Studiokomplex, und gerade deshalb ein wenig bedrohlich.",
  },
  {
    id: "old-camcorder",
    ambienceId: "video-camera",
    name: "Alte Videokamera",
    source: "Found-Footage-Anmutung",
    description: "Abgenutzt, kantig und so präsentiert, als wäre die letzte Aufnahme noch darin gefangen.",
  },
  {
    id: "black-stone-chess",
    ambienceId: "black-chess-set",
    name: "Schachfigurensatz aus schwarzem Stein",
    source: "Das siebente Siegel",
    description: "Matt schwarzer Stein, exakt aufgestellt. Ein stilles Spiel mit schwerem Unterton.",
  },
  {
    id: "cowboy-hat-spurs",
    ambienceId: "cowboy-hat-spurs",
    name: "Cowboyhut mit Sporen",
    source: "Western-Anspielung",
    description: "Staubige Romantik aus einem anderen Genre, sorgsam und fast nostalgisch präsentiert.",
  },
  {
    id: "jukebox-module",
    ambienceId: "diner-neon-jukebox",
    name: "Jukebox-Modul",
    source: "Roadmovie- und US-Kino-Flair",
    description: "Zerkratztes Chrom, rote Scheibe, ein Hauch Diner und schlechte Entscheidungen.",
  },
];

