export const SHIELD_CATALOG = {
  "clapperboard-shield": {
    id: "clapperboard-shield",
    type: "offhand",
    subtype: "shield",
    name: "Klappenbrett-Schild",
    icon: "director-board",
    minFloor: 1,
    blockChance: 16,
    blockValue: 2,
    source: "Studio Requisite",
    statMods: { reaction: 1 },
    description: "Leichtes Requisitenschild aus einem Klappenbrett. Schnell, handlich, gut für mobile Builds.",
  },
  "riot-cop-shield": {
    id: "riot-cop-shield",
    type: "offhand",
    subtype: "shield",
    name: "Riot-Cop Shield",
    icon: "riot-shield",
    minFloor: 6,
    blockChance: 24,
    blockValue: 4,
    source: "Action-Set",
    statMods: { reaction: -1 },
    description: "Schweres Einsatzschild mit starker Defensive, aber träger Bewegung.",
  },
  "neon-diner-tray": {
    id: "neon-diner-tray",
    type: "offhand",
    subtype: "shield",
    name: "Neon-Diner Tray",
    icon: "tray",
    minFloor: 1,
    blockChance: 14,
    blockValue: 2,
    source: "Retro Diner",
    statMods: { charm: 1 },
    description: "Improvisierter Schutz aus einem Diner-Serviertablett. Elegant, aber nicht sonderlich robust.",
  },
  "stuntman-bracer": {
    id: "stuntman-bracer",
    type: "offhand",
    subtype: "shield",
    name: "Stuntman-Bracer",
    icon: "stunt-bracer",
    minFloor: 2,
    blockChance: 17,
    blockValue: 2,
    source: "Stunt Crew",
    statMods: { endurance: 1 },
    description: "Robuster Armschutz für riskante Stunts und harte Trefferfolgen.",
  },
  "mausoleum-plate": {
    id: "mausoleum-plate",
    type: "offhand",
    subtype: "shield",
    name: "Mausoleum Plate",
    icon: "crypt-plate",
    minFloor: 4,
    blockChance: 21,
    blockValue: 3,
    source: "Gothic Horror",
    statMods: { reaction: -1 },
    description: "Schwere Grabplatte aus kaltem Stein. Verlässlich, aber sperrig.",
  },
  "satellite-dish-guard": {
    id: "satellite-dish-guard",
    type: "offhand",
    subtype: "shield",
    name: "Satellite Dish Guard",
    icon: "sat-dish",
    minFloor: 2,
    blockChance: 15,
    blockValue: 2,
    source: "Sci-Fi Set",
    statMods: { precision: 1 },
    description: "Technischer Reflektor-Schutz mit sauberer Linienführung und gutem Timing.",
  },
  "taxi-door-shield": {
    id: "taxi-door-shield",
    type: "offhand",
    subtype: "shield",
    name: "Taxi Door Shield",
    icon: "cab-door",
    minFloor: 4,
    blockChance: 19,
    blockValue: 3,
    source: "Urban Thriller",
    statMods: { endurance: 1, precision: -1 },
    description: "Abgerissene Autotür als urbanes Notschild. Klobig, aber zäh.",
  },
  "showmaster-aegis": {
    id: "showmaster-aegis",
    type: "offhand",
    subtype: "shield",
    name: "Showmaster Aegis",
    icon: "show-aegis",
    minFloor: 2,
    blockChance: 13,
    blockValue: 2,
    source: "TV-Studio",
    statMods: { strength: -1, charm: 1 },
    description: "Blendender Show-Schutz für große Auftritte und kleine Tricks.",
  },
  "fire-escape-buckler": {
    id: "fire-escape-buckler",
    type: "offhand",
    subtype: "shield",
    name: "Fire Escape Buckler",
    icon: "fire-escape",
    minFloor: 2,
    blockChance: 18,
    blockValue: 2,
    source: "Slasher Backlot",
    statMods: { reaction: 1 },
    description: "Leichter Metallschutz aus einem Feuerleiter-Segment. Schnell im Handling.",
  },
  "knight-prop-tower": {
    id: "knight-prop-tower",
    type: "offhand",
    subtype: "shield",
    name: "Knight Prop Tower",
    icon: "knight-tower",
    minFloor: 6,
    blockChance: 23,
    blockValue: 4,
    source: "Historienfilm",
    statMods: { strength: 1, reaction: -1 },
    description: "Breites Turnier-Requisit mit hoher Deckung und massivem Gewicht.",
  },
  "lab-containment-shield": {
    id: "lab-containment-shield",
    type: "offhand",
    subtype: "shield",
    name: "Lab Containment Shield",
    icon: "containment-panel",
    minFloor: 4,
    blockChance: 17,
    blockValue: 3,
    source: "Creature Feature",
    statMods: { nerves: 1 },
    description: "Versiegeltes Schutzpanel aus dem Laborbereich. Stabil gegen das Unbekannte.",
  },
  "projection-booth-plate": {
    id: "projection-booth-plate",
    type: "offhand",
    subtype: "shield",
    name: "Projection Booth Plate",
    icon: "projection-plate",
    minFloor: 4,
    blockChance: 20,
    blockValue: 3,
    source: "Altes Kino",
    statMods: { precision: 1 },
    description: "Projektorplatte mit solidem Kern und gutem Blick für Winkel.",
  },
  "ice-hockey-chest-guard": {
    id: "ice-hockey-chest-guard",
    type: "offhand",
    subtype: "shield",
    name: "Ice Hockey Chest Guard",
    icon: "hockey-guard",
    minFloor: 6,
    blockChance: 22,
    blockValue: 3,
    source: "Camp Slasher",
    statMods: { endurance: 1, reaction: -1 },
    description: "Sportlicher Brust- und Armschutz mit guter Standfestigkeit, aber etwas träge.",
  },
  "cathedral-reliquary-guard": {
    id: "cathedral-reliquary-guard",
    type: "offhand",
    subtype: "shield",
    name: "Cathedral Reliquary Guard",
    icon: "reliquary-guard",
    minFloor: 4,
    blockChance: 18,
    blockValue: 3,
    source: "Exorzismus-Set",
    statMods: { nerves: 1 },
    description: "Gesegnet wirkender Reliquienschutz für starke Nerven in düsteren Räumen.",
  },
  "paparazzi-flash-shield": {
    id: "paparazzi-flash-shield",
    type: "offhand",
    subtype: "shield",
    name: "Paparazzi Flash Shield",
    icon: "flash-guard",
    minFloor: 3,
    blockChance: 12,
    blockValue: 2,
    source: "Celebrity Horror",
    statMods: { reaction: 1, precision: 1, nerves: -1 },
    description: "Leichter Blitzreflektor, der Sicht und Tempo verbessert, aber die Ruhe kostet.",
  },
};

export const OFFHAND_CATALOG = SHIELD_CATALOG;
