import {
  WIDTH,
  HEIGHT,
  TILE_SIZE,
  TILE_GAP,
  BOARD_PADDING,
  ROOM_ATTEMPTS,
  MIN_ROOM_SIZE,
  MAX_ROOM_SIZE,
  LOG_LIMIT,
  HIGHSCORE_KEY,
  HIGHSCORE_STORAGE_VERSION,
  HIGHSCORE_VERSION_KEY,
  VISION_RADIUS,
  BASE_HIT_CHANCE,
  MIN_HIT_CHANCE,
  MAX_HIT_CHANCE,
  MIN_CRIT_CHANCE,
  MAX_CRIT_CHANCE,
  TILE,
  MONSTER_CATALOG,
  WEAPON_CATALOG,
  OFFHAND_CATALOG,
  DOOR_TYPE,
  LOCK_COLORS,
  PROP_CATALOG,
  DISPLAY_CASE_AMBIENCE,
} from '../data.mjs';
import {
  HERO_CLASSES,
  getHeroClassAssets,
  getUnlockedMonsterRank,
  getEnemyCountForFloor,
  getLegacySpecialMonsterSpawnChance,
  getHealingConsumableCountForFloor,
  shouldSpawnFloorWeapon,
  shouldSpawnFloorShield,
  shouldSpawnChest,
  getChestCountForFloor,
  getLockedDoorCountForFloor,
  shouldPlaceLockedRoomChest,
  getLevelUpRewards,
  NON_ICONIC_MONSTER_WEIGHT_BONUS,
  ICONIC_MONSTER_WEIGHT_PENALTY,
  ITEM_RARITY_MODIFIER_COUNTS,
  getEquipmentRarityWeights,
} from '../balance.mjs';
import {
  getNutritionMax,
  getNutritionStart,
  clampNutritionValue,
  getHungerState,
  getHungerStateLabel,
  getHungerStateMessage,
  HUNGER_STATE,
  NUTRITION_COST_PER_ACTION,
  DAMAGE_PER_ACTION_WHILE_DYING,
} from '../nutrition.mjs';
import { ITEM_DEFS } from '../item-defs.mjs';
import {
  buildStudioAnnouncement,
  formatArchetypeLabel,
  formatStudioLabel,
  formatStudioWithArchetype,
  getArchetypeForFloor,
} from '../studio-theme.mjs';

const OPTIONS_KEY = 'dungeon-rogue-options';
const HERO_NAME_KEY = 'movieverse-hero-name';
const HERO_CLASS_KEY = 'movieverse-hero-class';
const DEFAULT_HERO_NAME = 'Final Girl';
const DEFAULT_HERO_CLASS = 'filmstar';
const CHOICE_ACTIONS = {
  healingConsumable: ['use', 'store', 'leave'],
  consumable: ['use', 'store', 'leave'],
  food: ['eat', 'store', 'leave'],
  weapon: ['equip', 'store', 'leave'],
  offhand: ['equip', 'store', 'leave'],
};
const STAIR_ACTIONS = ['change-floor', 'stay'];

export function createAppConfig({ runtimeRandomApi, foodLootPipeline }) {
  return {
    WIDTH,
    HEIGHT,
    TILE_SIZE,
    TILE_GAP,
    BOARD_PADDING,
    ROOM_ATTEMPTS,
    MIN_ROOM_SIZE,
    MAX_ROOM_SIZE,
    LOG_LIMIT,
    HIGHSCORE_KEY,
    HIGHSCORE_STORAGE_VERSION,
    HIGHSCORE_VERSION_KEY,
    VISION_RADIUS,
    BASE_HIT_CHANCE,
    MIN_HIT_CHANCE,
    MAX_HIT_CHANCE,
    MIN_CRIT_CHANCE,
    MAX_CRIT_CHANCE,
    TILE,
    MONSTER_CATALOG,
    WEAPON_CATALOG,
    OFFHAND_CATALOG,
    DOOR_TYPE,
    LOCK_COLORS,
    PROP_CATALOG,
    DISPLAY_CASE_AMBIENCE,
    HERO_CLASSES,
    getHeroClassAssets,
    getUnlockedMonsterRank,
    getEnemyCountForFloor,
    getLegacySpecialMonsterSpawnChance,
    getHealingConsumableCountForFloor,
    shouldSpawnFloorWeapon: (floorNumber) => shouldSpawnFloorWeapon(floorNumber, runtimeRandomApi.randomChance()),
    shouldSpawnFloorShield: (floorNumber) => shouldSpawnFloorShield(floorNumber, runtimeRandomApi.randomChance()),
    shouldSpawnChest: (floorNumber) => shouldSpawnChest(floorNumber, runtimeRandomApi.randomChance()),
    getChestCountForFloor: (floorNumber) => getChestCountForFloor(floorNumber, runtimeRandomApi.randomChance()),
    getLockedDoorCountForFloor: (floorNumber) => getLockedDoorCountForFloor(floorNumber, runtimeRandomApi.randomChance()),
    shouldPlaceLockedRoomChest: () => shouldPlaceLockedRoomChest(runtimeRandomApi.randomChance()),
    getLevelUpRewards,
    NON_ICONIC_MONSTER_WEIGHT_BONUS,
    ICONIC_MONSTER_WEIGHT_PENALTY,
    ITEM_RARITY_MODIFIER_COUNTS,
    getEquipmentRarityWeights,
    buildFoodItemsForBudget: foodLootPipeline.buildFoodItemsForBudget,
    rollFoodBudget: foodLootPipeline.rollFoodBudget,
    splitFoodBudget: foodLootPipeline.splitFoodBudget,
    rollMonsterPlannedDrop: foodLootPipeline.rollMonsterPlannedDrop,
    ITEM_DEFS,
    OPTIONS_KEY,
    HERO_NAME_KEY,
    HERO_CLASS_KEY,
    DEFAULT_HERO_NAME,
    DEFAULT_HERO_CLASS,
    CHOICE_ACTIONS,
    STAIR_ACTIONS,
    formatStudioLabel,
    formatArchetypeLabel,
    formatStudioWithArchetype,
    buildStudioAnnouncement,
    getArchetypeForFloor,
    getNutritionMax,
    getNutritionStart,
    clampNutritionValue,
    getHungerState,
    getHungerStateLabel,
    getHungerStateMessage,
    HUNGER_STATE,
    NUTRITION_COST_PER_ACTION,
    DAMAGE_PER_ACTION_WHILE_DYING,
  };
}
