export const WIDTH = 50;
export const HEIGHT = 36;
export const TILE_SIZE = 28;
export const TILE_GAP = 2;
export const BOARD_PADDING = 8;
export const LOG_LIMIT = 12;
export const HIGHSCORE_KEY = "dungeon-rogue-highscores";
export const HIGHSCORE_STORAGE_VERSION = "2";
export const HIGHSCORE_VERSION_KEY = "dungeon-rogue-highscores-version";
export const HIGHSCORE_LAST_ENTRY_KEY = "dungeon-rogue-highscores-last-entry";
export {
  ROOM_ATTEMPTS,
  MIN_ROOM_SIZE,
  MAX_ROOM_SIZE,
  VISION_RADIUS,
  BASE_HIT_CHANCE,
  MIN_HIT_CHANCE,
  MAX_HIT_CHANCE,
  MIN_CRIT_CHANCE,
  MAX_CRIT_CHANCE,
} from './balance.mjs';

export const TILE = {
  WALL: "#",
  FLOOR: ".",
  PLAYER: "@",
  ENEMY: "G",
  POTION: "!",
  KEY: "k",
  DOOR_CLOSED: "+",
  DOOR_OPEN: "/",
  STAIRS_DOWN: ">",
  STAIRS_UP: "<",
  CHEST: "C",
  SHOWCASE: "V",
};

export const DOOR_TYPE = {
  NONE: "none",
  NORMAL: "normal",
  LOCKED: "locked",
};

export const LOCK_COLORS = ["green", "blue"];
export const MONSTER_MOBILITY = {
  LOCAL: "local",
  ROAMING: "roaming",
  RELENTLESS: "relentless",
};

export const MONSTER_MOBILITY_LABELS = {
  [MONSTER_MOBILITY.LOCAL]: "Reviertreu",
  [MONSTER_MOBILITY.ROAMING]: "Mobil",
  [MONSTER_MOBILITY.RELENTLESS]: "Jagdend",
};

export const MONSTER_RETREAT_PROFILE = {
  NONE: "none",
  CAUTIOUS: "cautious",
  COWARDLY: "cowardly",
};

export const MONSTER_RETREAT_LABELS = {
  [MONSTER_RETREAT_PROFILE.NONE]: "Standhaft",
  [MONSTER_RETREAT_PROFILE.CAUTIOUS]: "Vorsichtig",
  [MONSTER_RETREAT_PROFILE.COWARDLY]: "Fluchtbereit",
};

export const MONSTER_HEALING_PROFILE = {
  NONE: "none",
  SLOW: "slow",
  STEADY: "steady",
  LURKING: "lurking",
};

export const MONSTER_HEALING_LABELS = {
  [MONSTER_HEALING_PROFILE.NONE]: "Keine",
  [MONSTER_HEALING_PROFILE.SLOW]: "Langsam",
  [MONSTER_HEALING_PROFILE.STEADY]: "Stetig",
  [MONSTER_HEALING_PROFILE.LURKING]: "Nur außerhalb des Kampfes",
};

export const MONSTER_CATALOG = [
  {
    id: "bates",
    name: "Norman Bates",
    rank: 1,
    behavior: "dormant",
    behaviorLabel: "Schläfer",
    description: "Wirkt harmlos und unscheinbar, wird nach einem Angriff jedoch plötzlich tödlich.",
    strength: 3,
    precision: 4,
    reaction: 3,
    nerves: 3,
    intelligence: 5,
    hp: 10,
    xpReward: 12,
    aggroRadius: 2,
    canOpenDoors: true,
    special: "Wird erst nach einem Angriff wirklich aggressiv.",
  },
  {
    id: "motel-shlurfer",
    name: "Motel-Schlurfer",
    rank: 1,
    behavior: "wanderer",
    behaviorLabel: "Schlurfer",
    description: "Ein verwahrloster Schrecken aus schmutzigen Fluren und vergessenen Zimmern.",
    strength: 2,
    precision: 2,
    reaction: 2,
    nerves: 1,
    intelligence: 2,
    hp: 7,
    xpReward: 6,
    aggroRadius: 3,
    canOpenDoors: true,
    special: "Wirkt träge, rückt in engen Gängen aber hartnäckig nach.",
  },
  {
    id: "kellerkriecher",
    name: "Kellerkriecher",
    rank: 1,
    behavior: "wanderer",
    behaviorLabel: "Kriecher",
    description: "Ein huschender Schrecken aus dem Dunkel, der lieber aus Winkeln angreift.",
    strength: 1,
    precision: 3,
    reaction: 3,
    nerves: 1,
    intelligence: 1,
    hp: 6,
    xpReward: 6,
    aggroRadius: 3,
    canOpenDoors: false,
    special: "Ist in engen Räumen und Ecken besonders unangenehm.",
  },

  {
    id: "ghostface",
    name: "Ghostface",
    rank: 2,
    behavior: "stalker",
    behaviorLabel: "Verfolger",
    description: "Nimmt früh die Spur auf und lässt von seiner Beute meist nicht mehr ab.",
    strength: 4,
    precision: 5,
    reaction: 5,
    nerves: 3,
    intelligence: 4,
    hp: 12,
    xpReward: 15,
    aggroRadius: 8,
    offHand: "clapperboard-shield",
    canOpenDoors: true,
    special: "Bleibt früh an seiner Beute dran und fängt Hiebe mit seinem Rig ab.",
  },
  {
    id: "maskierter-nachahmer",
    name: "Maskierter Nachahmer",
    rank: 2,
    behavior: "stalker",
    behaviorLabel: "Verfolger",
    description: "Ein billiger Slasher-Abklatsch, der früh Druck macht und selten locker lässt.",
    strength: 2,
    precision: 3,
    reaction: 3,
    nerves: 2,
    intelligence: 2,
    hp: 8,
    xpReward: 8,
    aggroRadius: 6,
    canOpenDoors: true,
    special: "Nimmt früh die Verfolgung auf.",
  },
  {
    id: "videotheken-stalker",
    name: "Videotheken-Stalker",
    rank: 2,
    behavior: "stalker",
    behaviorLabel: "Jäger",
    description: "Zwischen Filmplakaten und Staubregalen wirkt er fehl am Platz – bis er lossprintet.",
    strength: 2,
    precision: 3,
    reaction: 4,
    nerves: 2,
    intelligence: 2,
    hp: 8,
    xpReward: 8,
    aggroRadius: 5,
    canOpenDoors: true,
    special: "Reagiert schnell auf Sichtkontakt.",
  },

  {
    id: "chucky",
    name: "Chucky",
    rank: 3,
    behavior: "wanderer",
    behaviorLabel: "Wirrling",
    description: "Klein, flink und nervtötend unberechenbar.",
    strength: 4,
    precision: 5,
    reaction: 6,
    nerves: 2,
    intelligence: 4,
    hp: 11,
    xpReward: 18,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Bewegt sich häufig unberechenbar und erstaunlich flink.",
  },
  {
    id: "besessene-puppe",
    name: "Besessene Puppe",
    rank: 3,
    behavior: "wanderer",
    behaviorLabel: "Wirrling",
    description: "Klein, hektisch und schwer einzuschätzen, wenn sie erst einmal in Bewegung ist.",
    strength: 2,
    precision: 3,
    reaction: 4,
    nerves: 1,
    intelligence: 2,
    hp: 7,
    xpReward: 10,
    aggroRadius: 4,
    canOpenDoors: false,
    special: "Bewegt sich oft unvorhersehbar.",
  },
  {
    id: "gremlin",
    name: "Gremlin",
    rank: 3,
    behavior: "trickster",
    behaviorLabel: "Störenfried",
    description: "Ein kicherndes Sabotagevieh, das mehr Chaos anrichtet, als seine Größe vermuten lässt.",
    strength: 2,
    precision: 3,
    reaction: 4,
    nerves: 1,
    intelligence: 2,
    hp: 8,
    xpReward: 10,
    aggroRadius: 4,
    canOpenDoors: false,
    special: "Wechselt gern abrupt die Richtung und stört den Kampfablauf.",
  },

  {
    id: "myers",
    name: "Michael Myers",
    rank: 4,
    behavior: "juggernaut",
    behaviorLabel: "Unerbittlich",
    description: "Langsam, schweigsam und von bedrückender Beharrlichkeit.",
    strength: 7,
    precision: 4,
    reaction: 3,
    nerves: 5,
    intelligence: 3,
    hp: 20,
    xpReward: 24,
    aggroRadius: 7,
    canOpenDoors: false,
    special: "Regeneriert langsam, wenn er längere Zeit nicht getroffen wird.",
  },
  {
    id: "stummer-maskenträger",
    name: "Stummer Maskenträger",
    rank: 4,
    behavior: "juggernaut",
    behaviorLabel: "Unerbittlich",
    description: "Schweigsam, langsam und mit genau der Art von Präsenz, die Korridore leer macht.",
    strength: 4,
    precision: 2,
    reaction: 2,
    nerves: 3,
    intelligence: 1,
    hp: 13,
    xpReward: 13,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Setzt stetig nach, wenn er dich einmal gesehen hat.",
  },
  {
    id: "friedhofsschlurfer",
    name: "Friedhofsschlurfer",
    rank: 4,
    behavior: "juggernaut",
    behaviorLabel: "Untoter",
    description: "Ein schwerfälliger Untoter, der weniger jagt als einfach immer näher kommt.",
    strength: 4,
    precision: 2,
    reaction: 1,
    nerves: 3,
    intelligence: 1,
    hp: 14,
    xpReward: 13,
    aggroRadius: 4,
    canOpenDoors: false,
    special: "Besonders zäh für seine Stufe.",
  },

  {
    id: "jason",
    name: "Jason Voorhees",
    rank: 5,
    behavior: "juggernaut",
    behaviorLabel: "Schlächter",
    description: "Zäh, schwer zu stoppen und im Nahkampf brutal.",
    strength: 8,
    precision: 4,
    reaction: 3,
    nerves: 5,
    intelligence: 3,
    hp: 22,
    xpReward: 28,
    aggroRadius: 7,
    canOpenDoors: false,
    special: "Rückt stoisch und ohne Hast näher.",
  },
  {
    id: "camp-schlaechter",
    name: "Camp-Schlächter",
    rank: 5,
    behavior: "juggernaut",
    behaviorLabel: "Schlächter",
    description: "Ein roher Killer aus Lagerfeuerlegenden und Blutspuren im Unterholz.",
    strength: 5,
    precision: 3,
    reaction: 2,
    nerves: 3,
    intelligence: 1,
    hp: 15,
    xpReward: 16,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Im Nahkampf gefährlicher als auf Distanz.",
  },
  {
    id: "mutierter-hinterwaeldler",
    name: "Mutierter Hinterwäldler",
    rank: 5,
    behavior: "juggernaut",
    behaviorLabel: "Brecher",
    description: "Mehr rohe Masse als Mensch – laut, brutal und schwer kleinzukriegen.",
    strength: 5,
    precision: 2,
    reaction: 2,
    nerves: 3,
    intelligence: 1,
    hp: 16,
    xpReward: 16,
    aggroRadius: 5,
    canOpenDoors: false,
    special: "Hält spürbar mehr aus als andere Gegner seiner Stufe.",
  },

  {
    id: "freddy",
    name: "Freddy Krüger",
    rank: 6,
    behavior: "stalker",
    behaviorLabel: "Jäger",
    description: "Clever, boshaft und überraschend aggressiv, sobald er Druck wittert.",
    strength: 6,
    precision: 6,
    reaction: 5,
    nerves: 4,
    intelligence: 6,
    hp: 18,
    xpReward: 32,
    aggroRadius: 9,
    offHand: "neon-diner-tray",
    canOpenDoors: true,
    special: "Führt seine Klauen mit einer improvisierten Boiler-Platte als Schutz.",
  },
  {
    id: "traumwandler",
    name: "Traumwandler",
    rank: 6,
    behavior: "stalker",
    behaviorLabel: "Jäger",
    description: "Eine flackernde Gestalt, die sich anfühlt, als käme sie aus einem schlechten Traum.",
    strength: 4,
    precision: 4,
    reaction: 4,
    nerves: 3,
    intelligence: 4,
    hp: 13,
    xpReward: 20,
    aggroRadius: 7,
    canOpenDoors: true,
    special: "Taucht plötzlich auf und setzt dann sofort nach.",
  },
  {
    id: "kesselraum-peiniger",
    name: "Kesselraum-Peiniger",
    rank: 6,
    behavior: "stalker",
    behaviorLabel: "Peiniger",
    description: "Schweiß, Dampf und Metall begleiten diesen Jäger auf Schritt und Tritt.",
    strength: 4,
    precision: 4,
    reaction: 3,
    nerves: 3,
    intelligence: 4,
    hp: 14,
    xpReward: 20,
    aggroRadius: 7,
    canOpenDoors: true,
    special: "Bleibt in mittlerer Distanz hartnäckig auf dem Ziel.",
  },

  {
    id: "pennywise",
    name: "Pennywise",
    rank: 7,
    behavior: "trickster",
    behaviorLabel: "Trickser",
    description: "Spielt mit Distanz, Verunsicherung und plötzlichen Ausbrüchen von Gewalt.",
    strength: 6,
    precision: 5,
    reaction: 5,
    nerves: 5,
    intelligence: 7,
    hp: 21,
    xpReward: 38,
    aggroRadius: 7,
    canOpenDoors: true,
    special: "Erholt sich leicht, wenn er sich aus dem direkten Kampf löst.",
  },
  {
    id: "kanalclown",
    name: "Kanalclown",
    rank: 7,
    behavior: "trickster",
    behaviorLabel: "Trickser",
    description: "Ein grinsender Schrecken, der Unsicherheit fast ebenso gut einsetzt wie Gewalt.",
    strength: 4,
    precision: 4,
    reaction: 4,
    nerves: 4,
    intelligence: 5,
    hp: 15,
    xpReward: 24,
    aggroRadius: 5,
    canOpenDoors: true,
    special: "Löst sich leichter aus dem direkten Schlagabtausch.",
  },
  {
    id: "gestaltlaeufer",
    name: "Gestaltläufer",
    rank: 7,
    behavior: "trickster",
    behaviorLabel: "Irrbild",
    description: "Nie ganz dort, wo man ihn erwartet, und nie so harmlos, wie er kurz wirkt.",
    strength: 4,
    precision: 4,
    reaction: 5,
    nerves: 3,
    intelligence: 5,
    hp: 14,
    xpReward: 24,
    aggroRadius: 5,
    canOpenDoors: true,
    special: "Wechselt gern zwischen Annäherung und Rückzug.",
  },

  {
    id: "xenomorph",
    name: "Xenomorph",
    rank: 8,
    behavior: "stalker",
    behaviorLabel: "Raubtier",
    description: "Extrem schnell und in engen Gängen nahezu pausenlos auf Jagd.",
    strength: 8,
    precision: 6,
    reaction: 7,
    nerves: 3,
    intelligence: 4,
    hp: 22,
    xpReward: 45,
    aggroRadius: 10,
    canOpenDoors: false,
    special: "Sehr weite Wahrnehmung und aggressive Jagd.",
  },
  {
    id: "critter",
    name: "Critter",
    rank: 8,
    behavior: "stalker",
    behaviorLabel: "Beißer",
    description: "Klein, schnell und mit viel zu vielen Zähnen für seine Größe.",
    strength: 5,
    precision: 4,
    reaction: 5,
    nerves: 2,
    intelligence: 2,
    hp: 15,
    xpReward: 28,
    aggroRadius: 7,
    canOpenDoors: false,
    special: "Greift aggressiv an, sobald er Beute wittert.",
  },
  {
    id: "tunnelkriecher",
    name: "Tunnelkriecher",
    rank: 8,
    behavior: "stalker",
    behaviorLabel: "Raubtier",
    description: "Ein dürrer Jäger aus Schächten und Lüftungsgängen, schnell und unangenehm leise.",
    strength: 5,
    precision: 4,
    reaction: 5,
    nerves: 2,
    intelligence: 2,
    hp: 16,
    xpReward: 28,
    aggroRadius: 8,
    canOpenDoors: false,
    special: "Hat eine weite Wahrnehmung in engen Bereichen.",
  },

  {
    id: "predator",
    name: "Predator",
    rank: 9,
    behavior: "hunter",
    behaviorLabel: "Jagdprofi",
    description: "Beobachtet erst, wählt dann den Moment und schlägt präzise zu.",
    strength: 9,
    precision: 7,
    reaction: 6,
    nerves: 5,
    intelligence: 7,
    hp: 24,
    xpReward: 52,
    aggroRadius: 9,
    offHand: "satellite-dish-guard",
    canOpenDoors: true,
    special: "Trägt einen Jagdschutz am Arm und jagt zielstrebig.",
  },
  {
    id: "trophaeenjaeger",
    name: "Trophäenjäger",
    rank: 9,
    behavior: "hunter",
    behaviorLabel: "Jagdprofi",
    description: "Ein disziplinierter Killer, der seine Ziele beobachtet wie Beute.",
    strength: 6,
    precision: 5,
    reaction: 4,
    nerves: 4,
    intelligence: 5,
    hp: 18,
    xpReward: 34,
    aggroRadius: 6,
    canOpenDoors: true,
    special: "Nähert sich kontrolliert und greift erst im richtigen Moment an.",
  },
  {
    id: "soeldner-tracker",
    name: "Söldner-Tracker",
    rank: 9,
    behavior: "hunter",
    behaviorLabel: "Tracker",
    description: "Weniger Show, mehr Professionalität – ein kalter Verfolger mit sicherer Hand.",
    strength: 6,
    precision: 5,
    reaction: 4,
    nerves: 3,
    intelligence: 5,
    hp: 18,
    xpReward: 34,
    aggroRadius: 6,
    canOpenDoors: true,
    special: "Bleibt auf Distanz aufmerksam und drückt dann gezielt nach.",
  },

  {
    id: "vader",
    name: "Darth Vader",
    rank: 10,
    behavior: "hunter",
    behaviorLabel: "Dunkler Lord",
    description: "Ein spätes Elite-Monster mit eisiger Ruhe und überwältigender Präsenz.",
    strength: 11,
    precision: 7,
    reaction: 5,
    nerves: 6,
    intelligence: 8,
    hp: 29,
    xpReward: 68,
    aggroRadius: 11,
    canOpenDoors: true,
    special: "Jagt kalt, direkt und mit eiserner Disziplin.",
  },
  {
    id: "dunkler-vollstrecker",
    name: "Dunkler Vollstrecker",
    rank: 10,
    behavior: "hunter",
    behaviorLabel: "Vollstrecker",
    description: "Ein schwerer Elitegegner mit kalter Haltung und tödlicher Konsequenz.",
    strength: 8,
    precision: 5,
    reaction: 4,
    nerves: 5,
    intelligence: 6,
    hp: 21,
    xpReward: 44,
    aggroRadius: 8,
    canOpenDoors: true,
    special: "Setzt mit disziplinierter Härte nach.",
  },
  {
    id: "sternen-inquisitor",
    name: "Sternen-Inquisitor",
    rank: 10,
    behavior: "hunter",
    behaviorLabel: "Inquisitor",
    description: "Ruhig, kontrolliert und mit jener Autorität, die jeden Raum sofort verändert.",
    strength: 7,
    precision: 6,
    reaction: 4,
    nerves: 5,
    intelligence: 6,
    hp: 20,
    xpReward: 44,
    aggroRadius: 8,
    canOpenDoors: true,
    special: "Jagt ohne Hast, aber ohne jeden Zweifel.",
  },

  {
    id: "terminator",
    name: "Terminator",
    rank: 11,
    behavior: "hunter",
    behaviorLabel: "Unaufhaltsam",
    description: "Kalte Maschine, die sich nicht abschütteln lässt und jeden Fehler bestraft.",
    strength: 12,
    precision: 6,
    reaction: 4,
    nerves: 6,
    intelligence: 7,
    hp: 34,
    xpReward: 84,
    aggroRadius: 12,
    canOpenDoors: true,
    special: "Kann dir als einziger Gegner über Treppen auf andere Ebenen folgen.",
    canChangeFloors: true,
  },
  {
    id: "killerdrohne",
    name: "Killerdrohne",
    rank: 11,
    behavior: "hunter",
    behaviorLabel: "Maschine",
    description: "Präzise, kalt und frei von jedem Zögern – eher Protokoll als Persönlichkeit.",
    strength: 8,
    precision: 5,
    reaction: 4,
    nerves: 5,
    intelligence: 5,
    hp: 24,
    xpReward: 56,
    aggroRadius: 9,
    canOpenDoors: true,
    special: "Verfolgt Ziele zuverlässig und ohne Ermüdung.",
  },
  {
    id: "cyborg-vollstrecker",
    name: "Cyborg-Vollstrecker",
    rank: 11,
    behavior: "juggernaut",
    behaviorLabel: "Unaufhaltsam",
    description: "Mehr Metall als Mensch und nur einem Auftrag verpflichtet.",
    strength: 9,
    precision: 4,
    reaction: 3,
    nerves: 5,
    intelligence: 5,
    hp: 25,
    xpReward: 56,
    aggroRadius: 8,
    canOpenDoors: true,
    special: "Rückt stoisch vor und lässt sich kaum abschütteln.",
  },
];

export const WEAPON_CATALOG = {
  bates: {
    id: "kitchen-knife",
    name: "Küchenmesser",
    source: "Psycho",
    handedness: "one-handed",
    damage: 1,
    hitBonus: 1,
    critBonus: 0,
    description: "Schlichte, schnelle Klinge aus Psycho.",
  },
  ghostface: {
    id: "buck-knife",
    name: "Buck 120",
    source: "Scream",
    handedness: "one-handed",
    damage: 2,
    hitBonus: 1,
    critBonus: 1,
    description: "Das typische Jagdmesser von Ghostface.",
  },
  chucky: {
    id: "voodoo-knife",
    name: "Voodoo-Messer",
    source: "Child's Play",
    handedness: "one-handed",
    damage: 2,
    hitBonus: 1,
    critBonus: 0,
    description: "Klein, flink und ideal für fiese Treffer.",
  },
  myers: {
    id: "chef-knife",
    name: "Chefmesser",
    source: "Halloween",
    handedness: "one-handed",
    damage: 3,
    hitBonus: 0,
    critBonus: 0,
    description: "Die ikonische Klinge von Michael Myers.",
  },
  jason: {
    id: "machete",
    name: "Machete",
    source: "Friday the 13th",
    handedness: "two-handed",
    damage: 4,
    hitBonus: -1,
    critBonus: 0,
    description: "Schwer, brachial und direkt.",
  },
  freddy: {
    id: "claw-glove",
    name: "Klauenhandschuh",
    source: "A Nightmare on Elm Street",
    handedness: "one-handed",
    damage: 3,
    hitBonus: 1,
    critBonus: 1,
    description: "Freddys berüchtigter Handschuh mit Klingen.",
  },
  pennywise: {
    id: "fear-spike",
    name: "Albtraumklaue",
    source: "It",
    handedness: "one-handed",
    damage: 3,
    hitBonus: 0,
    critBonus: 1,
    description: "Unheimliche Manifestation aus It.",
  },
  xenomorph: {
    id: "acid-tail",
    name: "Säureschweif",
    source: "Alien",
    handedness: "two-handed",
    damage: 4,
    hitBonus: 0,
    critBonus: 1,
    description: "Tropfende Alien-Waffe mit bösem Finish.",
  },
  predator: {
    id: "wrist-blades",
    name: "Handgelenksklingen",
    source: "Predator",
    handedness: "one-handed",
    damage: 5,
    hitBonus: 1,
    critBonus: 1,
    description: "Präzise Jagdklingen des Predators.",
  },
  vader: {
    id: "lightsaber",
    name: "Lichtschwert",
    source: "Star Wars",
    handedness: "two-handed",
    damage: 6,
    hitBonus: -1,
    critBonus: 2,
    description: "Schwere dunkle Klinge von Darth Vader.",
  },
  terminator: {
    id: "sawed-off-shotgun",
    name: "Abgesägte Schrotflinte",
    source: "The Terminator",
    handedness: "two-handed",
    damage: 7,
    hitBonus: -1,
    critBonus: 1,
    description: "Wuchtige Filmwaffe des Terminators.",
  },
};

export const DUNGEON_WEAPON_TIERS = [
  {
    minFloor: 3,
    weapons: [
      {
        id: "stunt-baton",
        name: "Stunt-Schlagstock",
        source: "Studiofund",
        handedness: "one-handed",
        damage: 3,
        hitBonus: 1,
        critBonus: 0,
        description: "Solide Nahkampfwaffe aus einer schlecht gesicherten Requisitenkammer.",
      },
      {
        id: "stage-cleaver",
        name: "Bühnenbeil",
        source: "Backstage",
        handedness: "one-handed",
        damage: 4,
        hitBonus: 0,
        critBonus: 0,
        description: "Schwerer als ein Messer und deutlich weniger dezent.",
      },
    ],
  },
  {
    minFloor: 5,
    weapons: [
      {
        id: "ritual-dagger",
        name: "Ritualdolch",
        source: "Okulter Fund",
        handedness: "one-handed",
        damage: 4,
        hitBonus: 1,
        critBonus: 1,
        description: "Scharf, ausgewogen und ein wenig zu sauber für diesen Ort.",
      },
      {
        id: "chain-hook",
        name: "Kettenhaken",
        source: "Schlachthausset",
        handedness: "two-handed",
        damage: 5,
        hitBonus: 0,
        critBonus: 1,
        description: "Unhandlich, aber verheerend, wenn er trifft.",
      },
    ],
  },
  {
    minFloor: 8,
    weapons: [
      {
        id: "studio-halberd",
        name: "Studio-Hellebarde",
        source: "Archivkammer",
        handedness: "two-handed",
        damage: 6,
        hitBonus: 1,
        critBonus: 1,
        description: "Eine überrestaurierte Requisitenwaffe, die plötzlich erschreckend echt wirkt.",
      },
      {
        id: "execution-sabre",
        name: "Henkerssäbel",
        source: "Verbotene Sammlung",
        handedness: "one-handed",
        damage: 5,
        hitBonus: 2,
        critBonus: 1,
        description: "Spät gefunden, klar überlegen und genau deshalb selten.",
      },
    ],
  },
].map((monster) => {
  const relentlessIds = new Set([
    "ghostface",
    "maskierter-nachahmer",
    "videotheken-stalker",
    "myers",
    "stummer-maskenträger",
    "jason",
    "camp-schlaechter",
    "mutierter-hinterwaeldler",
    "pennywise",
    "kanalclown",
    "predator",
    "trophaeenjaeger",
    "soeldner-tracker",
    "vader",
    "vollstrecker",
    "inquisitor",
    "terminator",
  ]);
  const localIds = new Set([
    "bates",
    "kellerkriecher",
    "besessene-puppe",
    "gremlin",
    "friedhofsschlurfer",
    "critter",
  ]);
  const cautiousRetreatIds = new Set([
    "ghostface",
    "videotheken-stalker",
    "freddy",
    "traumwandler",
    "kesselraum-peiniger",
    "trophaeenjaeger",
    "soeldner-tracker",
  ]);
  const cowardlyRetreatIds = new Set([
    "bates",
    "pennywise",
    "kanalclown",
    "gestaltlaeufer",
  ]);
  const steadyHealingIds = new Set([
    "myers",
    "jason",
    "mutierter-hinterwaeldler",
    "terminator",
  ]);
  const lurkingHealingIds = new Set([
    "pennywise",
    "kanalclown",
    "gestaltlaeufer",
    "freddy",
    "traumwandler",
  ]);

  const mobility = relentlessIds.has(monster.id)
    ? MONSTER_MOBILITY.RELENTLESS
    : localIds.has(monster.id)
      ? MONSTER_MOBILITY.LOCAL
      : MONSTER_MOBILITY.ROAMING;
  const retreatProfile = cowardlyRetreatIds.has(monster.id)
    ? MONSTER_RETREAT_PROFILE.COWARDLY
    : cautiousRetreatIds.has(monster.id)
      ? MONSTER_RETREAT_PROFILE.CAUTIOUS
      : MONSTER_RETREAT_PROFILE.NONE;
  const healingProfile = steadyHealingIds.has(monster.id)
    ? MONSTER_HEALING_PROFILE.STEADY
    : lurkingHealingIds.has(monster.id)
      ? MONSTER_HEALING_PROFILE.LURKING
      : MONSTER_HEALING_PROFILE.SLOW;

  return {
    ...monster,
    mobility,
    mobilityLabel: MONSTER_MOBILITY_LABELS[mobility],
    retreatProfile,
    retreatLabel: MONSTER_RETREAT_LABELS[retreatProfile],
    healingProfile,
    healingLabel: MONSTER_HEALING_LABELS[healingProfile],
  };
});

export const SHIELD_CATALOG = {
  "clapperboard-shield": {
    id: "clapperboard-shield",
    type: "offhand",
    subtype: "shield",
    name: "Klappenbrett-Schild",
    icon: "director-board",
    minFloor: 1,
    blockChance: 16,
    blockValue: 2,
    source: "Studio Requisite",
    statMods: { reaction: 1 },
    description: "Leichtes Requisitenschild aus einem Klappenbrett. Schnell, handlich, gut für mobile Builds.",
  },
  "riot-cop-shield": {
    id: "riot-cop-shield",
    type: "offhand",
    subtype: "shield",
    name: "Riot-Cop Shield",
    icon: "riot-shield",
    minFloor: 6,
    blockChance: 24,
    blockValue: 4,
    source: "Action-Set",
    statMods: { reaction: -1 },
    description: "Schweres Einsatzschild mit starker Defensive, aber träger Bewegung.",
  },
  "neon-diner-tray": {
    id: "neon-diner-tray",
    type: "offhand",
    subtype: "shield",
    name: "Neon-Diner Tray",
    icon: "tray",
    minFloor: 1,
    blockChance: 14,
    blockValue: 2,
    source: "Retro Diner",
    statMods: { charm: 1 },
    description: "Improvisierter Schutz aus einem Diner-Serviertablett. Elegant, aber nicht sonderlich robust.",
  },
  "stuntman-bracer": {
    id: "stuntman-bracer",
    type: "offhand",
    subtype: "shield",
    name: "Stuntman-Bracer",
    icon: "stunt-bracer",
    minFloor: 2,
    blockChance: 17,
    blockValue: 2,
    source: "Stunt Crew",
    statMods: { endurance: 1 },
    description: "Robuster Armschutz für riskante Stunts und harte Trefferfolgen.",
  },
  "mausoleum-plate": {
    id: "mausoleum-plate",
    type: "offhand",
    subtype: "shield",
    name: "Mausoleum Plate",
    icon: "crypt-plate",
    minFloor: 4,
    blockChance: 21,
    blockValue: 3,
    source: "Gothic Horror",
    statMods: { reaction: -1 },
    description: "Schwere Grabplatte aus kaltem Stein. Verlässlich, aber sperrig.",
  },
  "satellite-dish-guard": {
    id: "satellite-dish-guard",
    type: "offhand",
    subtype: "shield",
    name: "Satellite Dish Guard",
    icon: "sat-dish",
    minFloor: 2,
    blockChance: 15,
    blockValue: 2,
    source: "Sci-Fi Set",
    statMods: { precision: 1 },
    description: "Technischer Reflektor-Schutz mit sauberer Linienführung und gutem Timing.",
  },
  "taxi-door-shield": {
    id: "taxi-door-shield",
    type: "offhand",
    subtype: "shield",
    name: "Taxi Door Shield",
    icon: "cab-door",
    minFloor: 4,
    blockChance: 19,
    blockValue: 3,
    source: "Urban Thriller",
    statMods: { endurance: 1, precision: -1 },
    description: "Abgerissene Autotür als urbanes Notschild. Klobig, aber zäh.",
  },
  "showmaster-aegis": {
    id: "showmaster-aegis",
    type: "offhand",
    subtype: "shield",
    name: "Showmaster Aegis",
    icon: "show-aegis",
    minFloor: 2,
    blockChance: 13,
    blockValue: 2,
    source: "TV-Studio",
    statMods: { strength: -1, charm: 1 },
    description: "Blendender Show-Schutz für große Auftritte und kleine Tricks.",
  },
  "fire-escape-buckler": {
    id: "fire-escape-buckler",
    type: "offhand",
    subtype: "shield",
    name: "Fire Escape Buckler",
    icon: "fire-escape",
    minFloor: 2,
    blockChance: 18,
    blockValue: 2,
    source: "Slasher Backlot",
    statMods: { reaction: 1 },
    description: "Leichter Metallschutz aus einem Feuerleiter-Segment. Schnell im Handling.",
  },
  "knight-prop-tower": {
    id: "knight-prop-tower",
    type: "offhand",
    subtype: "shield",
    name: "Knight Prop Tower",
    icon: "knight-tower",
    minFloor: 6,
    blockChance: 23,
    blockValue: 4,
    source: "Historienfilm",
    statMods: { strength: 1, reaction: -1 },
    description: "Breites Turnier-Requisit mit hoher Deckung und massivem Gewicht.",
  },
  "lab-containment-shield": {
    id: "lab-containment-shield",
    type: "offhand",
    subtype: "shield",
    name: "Lab Containment Shield",
    icon: "containment-panel",
    minFloor: 4,
    blockChance: 17,
    blockValue: 3,
    source: "Creature Feature",
    statMods: { nerves: 1 },
    description: "Versiegeltes Schutzpanel aus dem Laborbereich. Stabil gegen das Unbekannte.",
  },
  "projection-booth-plate": {
    id: "projection-booth-plate",
    type: "offhand",
    subtype: "shield",
    name: "Projection Booth Plate",
    icon: "projection-plate",
    minFloor: 4,
    blockChance: 20,
    blockValue: 3,
    source: "Altes Kino",
    statMods: { precision: 1 },
    description: "Projektorplatte mit solidem Kern und gutem Blick für Winkel.",
  },
  "ice-hockey-chest-guard": {
    id: "ice-hockey-chest-guard",
    type: "offhand",
    subtype: "shield",
    name: "Ice Hockey Chest Guard",
    icon: "hockey-guard",
    minFloor: 6,
    blockChance: 22,
    blockValue: 3,
    source: "Camp Slasher",
    statMods: { endurance: 1, reaction: -1 },
    description: "Sportlicher Brust- und Armschutz mit guter Standfestigkeit, aber etwas träge.",
  },
  "cathedral-reliquary-guard": {
    id: "cathedral-reliquary-guard",
    type: "offhand",
    subtype: "shield",
    name: "Cathedral Reliquary Guard",
    icon: "reliquary-guard",
    minFloor: 4,
    blockChance: 18,
    blockValue: 3,
    source: "Exorzismus-Set",
    statMods: { nerves: 1 },
    description: "Gesegnet wirkender Reliquienschutz für starke Nerven in düsteren Räumen.",
  },
  "paparazzi-flash-shield": {
    id: "paparazzi-flash-shield",
    type: "offhand",
    subtype: "shield",
    name: "Paparazzi Flash Shield",
    icon: "flash-guard",
    minFloor: 3,
    blockChance: 12,
    blockValue: 2,
    source: "Celebrity Horror",
    statMods: { reaction: 1, precision: 1, nerves: -1 },
    description: "Leichter Blitzreflektor, der Sicht und Tempo verbessert, aber die Ruhe kostet.",
  },
};

export const OFFHAND_CATALOG = SHIELD_CATALOG;

export const PROP_CATALOG = [
  {
    id: "jason-hockey-mask",
    ambienceId: "jason-mask",
    name: "Hockeymaske von Jason",
    source: "Freitag der 13.",
    description: "Eine stumpf gewordene Eishockeymaske hinter Glas. Selbst still wirkt sie bedrohlich.",
  },
  {
    id: "bates-kitchen-knife",
    ambienceId: "bates-knife",
    name: "Küchenmesser von Norman Bates",
    source: "Psycho",
    description: "Schlichtes Stahlmesser aus einem Motel-Albtraum, sauber ausgeleuchtet in der Vitrine.",
  },
  {
    id: "freddy-claw-glove",
    ambienceId: "freddy-glove",
    name: "Gestreifter Handschuh mit Klingen",
    source: "A Nightmare on Elm Street",
    description: "Metall trifft Strickstoff und böse Erinnerungen. Die Klingen funkeln im Halbdunkel.",
  },
  {
    id: "myers-white-mask",
    ambienceId: "myers-mask",
    name: "Weiße Maske von Michael Myers",
    source: "Halloween",
    description: "Fast ausdruckslos und genau deshalb unheimlich. Hinter dem Glas noch stiller als sonst.",
  },
  {
    id: "ghostface-mask",
    ambienceId: "ghostface-mask",
    name: "Ghostface-Maske",
    source: "Scream",
    description: "Die langgezogene Fratze hängt in der Vitrine wie ein eingefrorener Schrei.",
  },
  {
    id: "chucky-doll",
    ambienceId: "chucky-doll",
    name: "Chucky-Puppe",
    source: "Child's Play",
    description: "Zu klein für den Raum und trotzdem sofort der Mittelpunkt. Jemand hat sie aufrecht gesetzt.",
  },
  {
    id: "lament-configuration",
    ambienceId: "puzzle-box",
    name: "Puzzle-Box",
    source: "Hellraiser",
    description: "Ein geometrisches Rätselobjekt mit falschem Goldglanz und einer unangenehmen Aura.",
  },
  {
    id: "leatherface-chainsaw",
    ambienceId: "chainsaw",
    name: "Kettensäge von Leatherface",
    source: "The Texas Chain Saw Massacre",
    description: "Verrostete Zähne, schweres Gehäuse, stumpfer Schrecken. Gut, dass Glas dazwischen ist.",
  },
  {
    id: "necronomicon",
    ambienceId: "necronomicon",
    name: "Necronomicon-Buch",
    source: "Evil Dead",
    description: "Leder, Nähte und etwas, das nicht wie Tinte aussieht. Die Seiten liegen halb offen.",
  },
  {
    id: "ring-vhs",
    ambienceId: "cursed-vhs",
    name: "VHS-Kassette aus dem Brunnenfluch",
    source: "Ring / The Ring",
    description: "Unspektakulär als Objekt, aber niemand bleibt lange davor stehen.",
  },
  {
    id: "indy-hat-whip",
    ambienceId: "indy-hat-whip",
    name: "Trilby-Hut und Peitsche",
    source: "Indiana Jones",
    description: "Abenteuer in Reinform: Leder, Staub und der Eindruck, dass die Vitrine zu klein ist.",
  },
  {
    id: "golden-idol",
    ambienceId: "golden-idol",
    name: "Goldene Götzenfigur",
    source: "Raiders of the Lost Ark",
    description: "Kompakt, schwer wirkend und mit genau dem Glanz, der schlechte Entscheidungen auslöst.",
  },
  {
    id: "fedora-stand",
    ambienceId: "fedora-whip",
    name: "Peitsche und Fedora auf einem Ständer",
    source: "Indiana-Jones-Anspielung",
    description: "Sorgsam präsentiert wie ein Museumsstück aus einer gluecklicheren Karriere.",
  },
  {
    id: "lightsaber-hilt",
    ambienceId: "lightsaber-hilt",
    name: "Lichtschwertgriff in Glas",
    source: "Star Wars",
    description: "Nur der Griff und doch sofort erkennbar. Die Vitrine spiegelt sein kaltes Metall.",
  },
  {
    id: "zorro-idol-mask",
    ambienceId: "zorro-mask",
    name: "Goldene Idol-Maske",
    source: "The Mask of Zorro",
    description: "Ein Gesicht aus Gold, stolz und leicht theatralisch. Fast zu edel für diesen Ort.",
  },
  {
    id: "flux-model",
    ambienceId: "flux-capacitor",
    name: "Flux-Kondensator-Modell",
    source: "Back to the Future",
    description: "Kabel, Lichtstreben und pure Filmwissenschaft. Hinter Glas wirkt es noch absurder.",
  },
  {
    id: "hoverboard",
    ambienceId: "hoverboard",
    name: "Hoverboard",
    source: "Back to the Future Part II",
    description: "Schräg aufgebockt wie ein Sportgerät aus einer Zukunft, die nie eingetroffen ist.",
  },
  {
    id: "ghostbusters-walkies",
    ambienceId: "ghostbusters-radios",
    name: "Walkie-Talkie-Set mit Geisterjäger-Logo",
    source: "Ghostbusters",
    description: "Leicht abgenutzte Funkgeräte, sauber ausgerichtet, als wären sie noch im Einsatz.",
  },
  {
    id: "ghost-trap",
    ambienceId: "ghost-trap",
    name: "Geisterfalle",
    source: "Ghostbusters",
    description: "Eine schwere Kiste voller Versprechen und Risiken. Zum Glück verriegelt.",
  },
  {
    id: "pke-meter",
    ambienceId: "pke-meter",
    name: "PKE-Meter",
    source: "Ghostbusters",
    description: "Ein seltsam technisches Gerät mit Antennen, Griff und sofortiger Wiedererkennbarkeit.",
  },
  {
    id: "red-balloon",
    ambienceId: "red-balloon",
    name: "Roter Luftballon",
    source: "Es",
    description: "In einer Vitrine eigentlich unsinnig. Genau deshalb wirkt er noch falscher.",
  },
  {
    id: "shining-key-board",
    ambienceId: "hotel-key-board",
    name: "Hotel-Zimmerschlüsselbrett",
    source: "The Shining",
    description: "Verwittertes Schlüsselbrett, leer und trotzdem voller Geschichten von Leuten, die nicht auscheckten.",
  },
  {
    id: "shining-axe",
    ambienceId: "shining-axe",
    name: "Axt im Holzsockel",
    source: "The Shining",
    description: "Wie eine Trophäe ausgestellt. Man merkt dem Holz die Gewalt noch an.",
  },
  {
    id: "crystal-skull",
    ambienceId: "crystal-skull",
    name: "Kristallschaedel",
    source: "Indiana Jones and the Kingdom of the Crystal Skull",
    description: "Zu glatt, zu klar, zu perfekt. Das Ding scheint jeden Winkel des Raums zu sehen.",
  },
  {
    id: "titanic-heart",
    ambienceId: "heart-jewel-box",
    name: "Herz in einer Schmuckschatulle",
    source: "Titanic",
    description: "Tiefblau und fehl am Platz zwischen all dem Horror. Gerade deshalb bleibt man kurz stehen.",
  },
  {
    id: "glass-bell-rose",
    ambienceId: "rose-under-glass",
    name: "Rose in einer Glasglocke",
    source: "Beauty and the Beast",
    description: "Fast zu märchenhaft für den Dungeon. Das Glas wirkt klarer als die Luft drumherum.",
  },
  {
    id: "film-clapper",
    ambienceId: "film-clapper",
    name: "Filmklappe mit eingebrannten Notizen",
    source: "Filmset",
    description: "Volle Produktionskritzeleien, halbe Brandspuren. Sie fühlt sich hier beinahe zuhause an.",
  },
  {
    id: "hollywood-trophy",
    ambienceId: "film-award",
    name: "Goldene Trophäe",
    source: "Hollywood-Motiv",
    description: "Eine Oscar-ähnliche Statue, stolz beleuchtet und etwas zu sauber für den Rest des Dungeons.",
  },
  {
    id: "terminator-bust",
    ambienceId: "terminator-jacket-glasses",
    name: "Sonnenbrille und Lederjacke auf Büste",
    source: "Terminator",
    description: "Die Pose verkauft Coolness, aber die Vitrine verrät eher eine Warnung.",
  },
  {
    id: "cyber-hand",
    ambienceId: "cyber-hand",
    name: "Cyberhand im Acrylblock",
    source: "Terminator 2",
    description: "Metallische Finger unter klarem Kunstharz. Ein eingefrorener Blick in eine schlechte Zukunft.",
  },
  {
    id: "motion-tracker",
    ambienceId: "motion-tracker",
    name: "Bewegungsmelder",
    source: "Aliens",
    description: "Militärisches Plastik und ein Display, das man instinktiv nicht blinken sehen will.",
  },
  {
    id: "facehugger-jar",
    ambienceId: "facehugger-tank",
    name: "Facehugger im Glasbehälter",
    source: "Alien",
    description: "Das Glas ist dick. Hoffentlich dick genug.",
  },
  {
    id: "amber-mosquito",
    ambienceId: "amber-mosquito",
    name: "Bernstein mit Mücke",
    source: "Jurassic Park",
    description: "Klein, unscheinbar und mit unverhältnismaessig großer Tragweite für die Popkultur.",
  },
  {
    id: "fantasy-labyrinth-artifact",
    ambienceId: "labyrinth-artifact",
    name: "Labyrinth-Artefakt",
    source: "Fantasy-Film-Anmutung",
    description: "Ein verschachtelter Würfel aus Ornamenten und Spiegelungen. Mehr Versprechen als Erklärung.",
  },
  {
    id: "badge-and-holster",
    ambienceId: "badge-holster",
    name: "Police-Badge und Revolver-Holster",
    source: "Cop-Kino-Anklang",
    description: "Dienstmarke und Lederholster, arrangiert wie ein letzter Rest harter Großstadtfilme.",
  },
  {
    id: "ballerina-music-box",
    ambienceId: "music-box",
    name: "Spieluhr mit Ballerina",
    source: "Horror- und Mystery-Filmklischee",
    description: "Zu filigran für diesen Dungeon, und gerade deshalb ein wenig bedrohlich.",
  },
  {
    id: "old-camcorder",
    ambienceId: "video-camera",
    name: "Alte Videokamera",
    source: "Found-Footage-Anmutung",
    description: "Abgenutzt, kantig und so präsentiert, als wäre die letzte Aufnahme noch darin gefangen.",
  },
  {
    id: "black-stone-chess",
    ambienceId: "black-chess-set",
    name: "Schachfigurensatz aus schwarzem Stein",
    source: "Das siebente Siegel",
    description: "Matt schwarzer Stein, exakt aufgestellt. Ein stilles Spiel mit schwerem Unterton.",
  },
  {
    id: "cowboy-hat-spurs",
    ambienceId: "cowboy-hat-spurs",
    name: "Cowboyhut mit Sporen",
    source: "Western-Anspielung",
    description: "Staubige Romantik aus einem anderen Genre, sorgsam und fast nostalgisch präsentiert.",
  },
  {
    id: "jukebox-module",
    ambienceId: "diner-neon-jukebox",
    name: "Jukebox-Modul",
    source: "Roadmovie- und US-Kino-Flair",
    description: "Zerkratztes Chrom, rote Scheibe, ein Hauch Diner und schlechte Entscheidungen.",
  },
];

export const DISPLAY_CASE_AMBIENCE = {
  "jason-mask": [
    "Hinter dem Glas starrt dich eine abgenutzte Hockeymaske an. Der Raum wirkt plötzlich stiller.",
    "Die Maske in der Vitrine sieht harmlos aus, bis man merkt, wie leer der Blick dahinter ist.",
    "Ein kaltes Schaudern zieht durch den Raum. Selbst hinter Glas wirkt diese Maske wie eine Warnung.",
  ],
  "bates-knife": [
    "In der Vitrine ruht ein schlichtes Küchenmesser. Gerade seine Alltäglichkeit macht es unheimlich.",
    "Das Messer wirkt unscheinbar, fast banal. Vielleicht ist genau das das Beunruhigende daran.",
    "Hinter Glas liegt eine Klinge, die nicht protzig sein muss, um bedrohlich zu wirken.",
  ],
  "freddy-glove": [
    "Metallene Klingen kratzen leise gegeneinander, obwohl sich nichts bewegt.",
    "Der Handschuh in der Vitrine sieht aus, als gehöre er eher in einen Albtraum als in ein Museum.",
    "Für einen Moment fühlt sich selbst Wachsein in diesem Raum nicht mehr ganz sicher an.",
  ],
  "myers-mask": [
    "Die bleiche Maske zeigt keine Regung. Gerade deshalb scheint sie dich anzustarren.",
    "Hinter Glas liegt ein leeres Gesicht, das unnatürlich viel Präsenz in den Raum bringt.",
    "Die Vitrine schützt die Maske. Das beruhigt dich weniger, als es sollte.",
  ],
  "ghostface-mask": [
    "Ein stummes Grinsen schwebt in der Vitrine. Der Raum fühlt sich an wie die Pause vor einem Anruf.",
    "Die Maske wirkt theatralisch und doch unangenehm ernst.",
    "Hinter Glas wartet ein Gesicht, das wie Spott und Drohung zugleich aussieht.",
  ],
  "chucky-doll": [
    "Die kleine Puppe sitzt reglos hinter Glas. Du könntest schwoeren, dass sie eben noch anders sass.",
    "Der Raum wirkt kindlicher als zuvor. Das macht ihn nur schlimmer.",
    "Hinter der Scheibe grinst etwas, das eigentlich viel zu klein sein sollte, um bedrohlich zu wirken.",
  ],
  "puzzle-box": [
    "Auf dem Sockel liegt eine kunstvoll gearbeitete Schatulle. Manche Rätsel sollten geschlossen bleiben.",
    "Die Box zieht den Blick an, als würde sie auf neugierige Haende warten.",
    "Je länger du das Muster der Schatulle ansiehst, desto mehr bereust du es.",
  ],
  chainsaw: [
    "Eine schwere Kettensäge wurde hier ausgestellt wie ein Kunstwerk. Der Raum riecht beinahe nach Öl.",
    "Hinter Glas ruht rohe Gewalt in Maschinenform.",
    "Die Kettensäge ist still. Gerade deshalb scheint der Raum auf ihr Erwachen zu warten.",
  ],
  necronomicon: [
    "Ein verwittertes Buch liegt aufgeschlagen im Glas. Es sieht aus, als wolle es gelesen werden.",
    "Die Seiten wirken alt, aber nicht friedlich alt.",
    "Etwas an diesem Buch sagt dir, dass Wissen manchmal nur eine andere Form von Gefahr ist.",
  ],
  "cursed-vhs": [
    "Eine alte Kassette steht einsam in der Vitrine. Der Raum summt leise, als wäre irgendwo ein Bildschirm an.",
    "Das Band hinter Glas wirkt harmlos, bis man zu lange hinsieht.",
    "Du hörst nichts. Trotzdem fühlt es sich an, als hätte gerade etwas begonnen zu laufen.",
  ],
  "indy-hat-whip": [
    "Hut und Peitsche ruhen hier wie Reliquien eines gefaehrlichen Abenteuers.",
    "Die Vitrine wirkt weniger wie ein Museum als wie der Anfang einer Expedition.",
    "Staub, Leder und Legenden scheinen an diesem Ensemble gleichermaßen zu haften.",
  ],
  "golden-idol": [
    "Eine kleine goldene Figur glitzert im Licht. Sie sieht aus, als hätte sie schon viele in Schwierigkeiten gebracht.",
    "Der Schatz in der Vitrine wirkt wertvoll genug, um töricht zu machen.",
    "Selbst hinter Glas hat diese Figur etwas von einer Versuchung mit Folgen.",
  ],
  "fedora-whip": [
    "Ein alter Hut und eine aufgerollte Peitsche lassen den Raum nach verlorenen Karten und engen Tempeln wirken.",
    "Diese Auslage riecht förmlich nach Staub, Risiko und schlechtem Timing.",
    "Die Vitrine zeigt keine Schätze, sondern die Werkzeuge derer, die sie überlebt haben.",
  ],
  "lightsaber-hilt": [
    "Ein unscheinbarer Metallgriff liegt hinter Glas. Trotzdem bekommt der Raum etwas Feierliches.",
    "Die Vitrine bewahrt nur einen Griff auf, aber dein Gefühl sagt dir, dass mehr darin steckt.",
    "Das Objekt wirkt still, konzentriert und gefaehrlicher, als seine Größe vermuten lässt.",
  ],
  "zorro-mask": [
    "Schwarzer Stoff und scharfe Konturen verleihen dem Raum plötzlich etwas von Bühne und Duell.",
    "Die Maske hinter Glas verspricht Eleganz, Tempo und einen Schnitt im richtigen Moment.",
    "Diese Vitrine strahlt mehr Stil als Sicherheit aus.",
  ],
  "flux-capacitor": [
    "Zwischen Leitungen und Lichtstreifen pulsiert eine seltsame Apparatur. Die Zeit fühlt sich hier kurz unsicher an.",
    "Das Gerät in der Vitrine sieht aus, als gehöre es nicht ganz in dieselbe Gegenwart wie du.",
    "Etwas an dieser Technik macht den Raum einen Augenblick lang unwirklich.",
  ],
  hoverboard: [
    "Ein futuristisches Brett wurde hier ausgestellt, als hätte jemand die Zukunft vergessen.",
    "Die Form wirkt verspielt, aber fehl am Platz in diesem Gemäuer.",
    "Die Vitrine zeigt ein Stück Leichtigkeit an einem Ort, der davon nichts wissen will.",
  ],
  "ghostbusters-radios": [
    "Zwei Funkgeräte ruhen in der Vitrine, als warteten sie noch immer auf einen Notruf.",
    "Der Raum fühlt sich an, als müsste jeden Moment jemand eine hektische Meldung durchgeben.",
    "Hinter Glas liegt Ausrüstung für Probleme, die man lieber nicht genauer benannt bekommt.",
  ],
  "ghost-trap": [
    "Das metallene Gerät auf dem Sockel wirkt klein für den Zweck, den es andeutet.",
    "Die Falle in der Vitrine sieht aus, als habe sie schon Dinge gehalten, die kein Käfig verdient.",
    "Der Raum wirkt plötzlich technischer, ohne dadurch weniger unheimlich zu werden.",
  ],
  "pke-meter": [
    "Ein sonderbares Messgerät ruht hinter Glas. Trotzdem hast du das Gefühl, es müsste hier laengst ausschlagen.",
    "Die Anzeige ist dunkel, aber der Raum fühlt sich nicht leer genug dafür an.",
    "Hinter der Scheibe liegt ein Werkzeug für Unsichtbares. Das ist nicht beruhigend.",
  ],
  "red-balloon": [
    "Ein einzelner roter Ballon wurde in der Vitrine befestigt. Seine Fröhlichkeit wirkt hier unten falsch.",
    "Das kräftige Rot im Glas stört die Dunkelheit des Raums auf unangenehme Weise.",
    "Etwas so Einfaches sollte nicht so bedrohlich wirken, und doch tut es das.",
  ],
  "hotel-key-board": [
    "Ein altes Schlüsselbrett hängt ausgestellt im Glas. Zu viele Haken sind leer.",
    "Die leeren Plätze auf dem Brett erzählen von Gästen, die wohl nicht ordentlich ausgecheckt haben.",
    "Der Raum wirkt plötzlich wie ein Flur, in dem Türen besser geschlossen blieben.",
  ],
  "shining-axe": [
    "Eine Axt wurde hier fast ehrfürchtig präsentiert. Das macht sie nur bedrohlicher.",
    "Das Werkzeug in der Vitrine wirkt weniger wie ein Fundstück als wie eine Erinnerung an Lärm hinter Holz.",
    "Der Raum scheint für einen Moment enger zu werden, als müsste etwas gleich durchbrechen.",
  ],
  "crystal-skull": [
    "Der Schädel aus klarem Material faengt das Licht auf unnatürliche Weise.",
    "Hinter Glas liegt etwas, das eher aufmerksam als tot wirkt.",
    "Das Objekt glänzt schön genug, um gefaehrlich zu sein.",
  ],
  "heart-jewel-box": [
    "In einer geöffneten Schatulle liegt ein Herzsymbol, das hier unten eher melancholisch als romantisch wirkt.",
    "Selbst Liebe sieht in diesem Raum aus wie eine Erinnerung mit schlechtem Ausgang.",
    "Die Vitrine zeigt etwas Zartes, und gerade deshalb wirkt es fehl am Platz.",
  ],
  "rose-under-glass": [
    "Eine einzelne Rose steht geschützt in der Vitrine. Ihre Schönheit beruhigt den Raum kein bisschen.",
    "Die Blume wirkt zu vollkommen für diesen Ort.",
    "Hinter Glas blüht etwas Sanftes, das im Dungeon fast unheimlicher wirkt als jede Klinge.",
  ],
  "film-clapper": [
    "Eine alte Filmklappe lehnt auf dem Sockel. Der Raum fühlt sich an, als hätte gerade eine Szene begonnen.",
    "Hinter Glas wartet das Zeichen für Action, aber niemand hat dir das Drehbuch gegeben.",
    "Die Klappe erinnert daran, dass dieser Ort sich manchmal mehr wie ein Set als wie ein Dungeon anfühlt.",
  ],
  "film-award": [
    "Eine goldene Trophäe glänzt in der Vitrine, als gaebe es hier unten etwas zu feiern.",
    "Der Preis hinter Glas wirkt wie ein schlechter Witz an einem Ort wie diesem.",
    "Selbst Ruhm sieht im Dungeon aus wie etwas, das zu spaet gekommen ist.",
  ],
  "terminator-jacket-glasses": [
    "Jacke und Brille ruhen wie Überreste jemandes, der selten um Erlaubnis bat.",
    "Der Raum bekommt durch diese Vitrine etwas Kaltes und Unausweichliches.",
    "Hinter Glas liegt die Uniform einer Entschlossenheit, die man nicht diskutiert.",
  ],
  "cyber-hand": [
    "Eine künstliche Hand ist im klaren Block konserviert. Ihre Finger sehen aus, als koennten sie sich jederzeit schließen.",
    "Metall und Gelenke ruhen still, aber nicht friedlich.",
    "Der Raum fühlt sich plötzlich an, als sei Menschliches hier nur noch eine Option.",
  ],
  "motion-tracker": [
    "Ein Ortungsgerät liegt hinter Glas, dunkel und still. In Gedanken hörst du trotzdem bereits das Piepen.",
    "Die Anzeige schläft, aber der Raum tut es nicht.",
    "Manche Geräte wirken selbst dann beunruhigend, wenn sie gerade nichts anzeigen.",
  ],
  "facehugger-tank": [
    "In einem Glaszylinder kauert etwas, das besser niemals lebendig aussah.",
    "Der Behälter hält das Wesen zurück. Das reicht nicht, um den Raum harmlos zu machen.",
    "Je kürzer du hinsiehst, desto klüger fühlst du dich.",
  ],
  "amber-mosquito": [
    "Ein Stück Bernstein mit eingeschlossenem Insekt glimmt warm im Licht. Etwas daran wirkt unverhältnismaessig bedrohlich.",
    "Die kleine Mücke im Stein erinnert daran, dass Katastrophen nicht gross beginnen müssen.",
    "Hinter Glas liegt ein winziger Ursprung für sehr große Fehler.",
  ],
  "labyrinth-artifact": [
    "Ein fremdartiges Artefakt mit verschlungenen Linien wurde hier ausgestellt. Es macht selbst den Rückweg verdächtig.",
    "Je länger du das Objekt ansiehst, desto weniger sicher bist du dir über die Form des Raums.",
    "Die Vitrine beherbergt etwas, das wirkt, als koenne es Wege verbiegen.",
  ],
  "badge-holster": [
    "Marke und Holster liegen nebeneinander wie Beweisstücke eines Falls mit schlechtem Ende.",
    "Der Raum riecht förmlich nach Neon, Regen und Entscheidungen unter Druck.",
    "Hinter Glas ruht Autorität, aber ohne jede Garantie auf Gerechtigkeit.",
  ],
  "music-box": [
    "Hinter Glas steht eine kleine Spieluhr. Du hörst keine Musik, und gerade das macht sie unheimlich.",
    "Die Ballerina wirkt, als müsse sie sich nur noch einmal drehen.",
    "Etwas so Zartes sollte den Raum nicht bedrohlicher machen, und doch geschieht genau das.",
  ],
  "video-camera": [
    "Eine verstaubte Kamera wurde hier ausgestellt, als hätte sie alles gesehen.",
    "Der Raum fühlt sich an, als würdest nicht nur du ihn beobachten.",
    "Hinter Glas liegt ein Auge aus einer anderen Zeit, und es wirkt nicht blind.",
  ],
  "black-chess-set": [
    "Auf dem Sockel stehen schwarze Figuren in perfekter Ordnung. Es sieht aus, als wäre laengst ein Zug gegen dich gemacht worden.",
    "Das Brettspiel in der Vitrine wirkt weniger wie Zeitvertreib als wie ein Urteil.",
    "Der Raum bekommt durch diese Figuren etwas von stiller, unausweichlicher Planung.",
  ],
  "cowboy-hat-spurs": [
    "Ein abgewetzter Hut und ein Paar Sporen erinnern an staubige Strassen und letzte Duelle.",
    "Selbst hier unten haftet diesen Dingen noch etwas von Weite und Gefahr an.",
    "Die Vitrine trägt den Geruch von Sonne, Leder und Entscheidungen, die man nur einmal trifft.",
  ],
  "diner-neon-jukebox": [
    "Ein Stück greller Americana leuchtet hinter Glas. Der Raum wirkt wie die Erinnerung an einen Ort, der nie sicher war.",
    "Zwischen Neon und Nostalgie liegt hier ein seltsamer Hauch von Gefahr.",
    "Die Vitrine summt fast nach Musik, obwohl nichts spielt.",
  ],
};

