import { createItemEquipmentApi } from './application/item-equipment.mjs';
import { createItemLootApi } from './application/item-loot.mjs';
import { createItemUiHelpers } from './application/item-ui-helpers.mjs';

export function createItemsApi(context) {
  const {
    getState,
    getCurrentFloorState,
    getMainHand,
    getOffHand,
    applyItemStatMods,
    cloneWeapon,
    cloneOffHandItem,
    createWeaponPickup,
    createOffHandPickup,
    createPotionPickup,
    createFoodPickup,
    formatWeaponDisplayName,
    formatWeaponReference,
    formatWeaponStats,
    formatOffHandStats,
    formatRarityLabel,
    getItemModifierSummary,
    addMessage,
    showChoiceModal,
    hideChoiceModal,
    endTurn,
    healPlayer,
    restoreNutrition,
    useConsumable,
    refreshNutritionState,
    renderSelf,
    applyStatusEffect,
    randomChance,
  } = context;

  const { buildEquipmentCompareModel } = createItemUiHelpers({
    formatRarityLabel,
    formatWeaponDisplayName,
    getItemModifierSummary,
  });

  const equipmentApi = createItemEquipmentApi({
    getState,
    getMainHand,
    applyItemStatMods,
    cloneWeapon,
    cloneOffHandItem,
    formatWeaponReference,
    addMessage,
    endTurn,
    healPlayer,
    restoreNutrition,
    useConsumable,
    refreshNutritionState,
    renderSelf,
    applyStatusEffect,
    randomChance,
  });

  const lootApi = createItemLootApi({
    getState,
    getCurrentFloorState,
    getMainHand,
    getOffHand,
    cloneWeapon,
    cloneOffHandItem,
    createWeaponPickup,
    createOffHandPickup,
    createPotionPickup,
    createFoodPickup,
    formatWeaponDisplayName,
    formatWeaponReference,
    formatWeaponStats,
    formatOffHandStats,
    addMessage,
    showChoiceModal,
    hideChoiceModal,
    endTurn,
    healPlayer,
    restoreNutrition,
    useConsumable,
    applyHealingConsumableEffect: equipmentApi.applyHealingConsumableEffect,
    renderSelf,
    buildEquipmentCompareModel,
    equipWeapon: equipmentApi.equipWeapon,
    equipOffHand: equipmentApi.equipOffHand,
  });

  return {
    tryPickupLoot: lootApi.tryPickupLoot,
    equipWeapon: equipmentApi.equipWeapon,
    canEquipOffHand: equipmentApi.canEquipOffHand,
    equipOffHand: equipmentApi.equipOffHand,
    openChest: lootApi.openChest,
    closeContainerLoot: lootApi.closeContainerLoot,
    toggleContainerLootSelection: lootApi.toggleContainerLootSelection,
    cycleContainerLootAction: lootApi.cycleContainerLootAction,
    moveContainerLootFocus: lootApi.moveContainerLootFocus,
    confirmContainerLootFocus: lootApi.confirmContainerLootFocus,
    takeSelectedContainerLoot: lootApi.takeSelectedContainerLoot,
    takeAllContainerLoot: lootApi.takeAllContainerLoot,
    resolvePotionChoice: lootApi.resolvePotionChoice,
    useInventoryItem: equipmentApi.useInventoryItem,
    quickUsePotion: equipmentApi.quickUsePotion,
    getHealingConsumableGroups: equipmentApi.getHealingConsumableGroups,
    getHealingOverlayState: equipmentApi.getHealingOverlayState,
    openHealingOverlay: equipmentApi.openHealingOverlay,
    closeHealingOverlay: equipmentApi.closeHealingOverlay,
    toggleHealingOverlay: equipmentApi.toggleHealingOverlay,
    cycleHealingOverlay: equipmentApi.cycleHealingOverlay,
    selectHealingOverlayFamily: equipmentApi.selectHealingOverlayFamily,
    useSelectedHealingConsumable: equipmentApi.useSelectedHealingConsumable,
    useHealingConsumableByFamily: equipmentApi.useHealingConsumableByFamily,
    cloneWeapon,
  };
}
