import { createFoodLootPipeline } from './application/food-loot-pipeline.mjs';
import { createInventoryStatsApi } from './application/inventory-stats.mjs';
import { applyItemStatMods } from './application/item-stat-mods.mjs';
import { createUiBindingsApi } from './application/ui-bindings.mjs';
import { createAppConfig } from './app/app-config.mjs';
import { appFactories } from './app/app-factories.mjs';
import { createAppUi } from './app/app-ui.mjs';
import { createAppBootstrap } from './app/bootstrap.mjs';
import { assembleCoreModules } from './app/core-assembly.mjs';
import { assembleGameplayModules } from './app/gameplay-assembly.mjs';
import { assembleInterfaceModules } from './app/interface-assembly.mjs';
import { createRuntimeActionsApi } from './app/runtime-actions.mjs';
import { createRuntimeContext } from './app/runtime-context.mjs';
import { createRuntimeRandomApi } from './app/runtime-random.mjs';
import { createRenderCycleApi } from './app/render-cycle.mjs';
import { createShowcaseAmbienceApi } from './ambience/narration/showcase-ambience.mjs';
import { createStartFlowApi } from './app/start-flow.mjs';
import { createRuntimeSupportApi } from './app/runtime-support.mjs';
import { createUiPreferencesApi } from './app/ui-preferences.mjs';
import { getLoreTooltip } from './content/lore-tooltips.mjs';
import {
  createBareHandsWeapon,
  cloneOffHandItem,
  getMainHand,
  getOffHand,
  getCombatWeapon,
  createEquipmentPresentationHelpers,
} from './equipment-helpers.mjs';
import { createInlineLoreTooltipBinder } from './ui/inline-lore-tooltips.mjs';
import { createTimestampedId } from './utils/id-tools.mjs';
import { clamp, createGrid, carveRoom, carveTunnel, roomsOverlap } from './utils.mjs';

let state;

const runtimeActionsApi = createRuntimeActionsApi();
const runtimeRandomApi = createRuntimeRandomApi();
const foodLootPipeline = createFoodLootPipeline({
  randomChance: runtimeRandomApi.randomChance,
});
const appConfig = createAppConfig({
  runtimeRandomApi,
  foodLootPipeline,
});
const appUi = createAppUi();
const createRuntimeId = (prefix) => createTimestampedId(prefix, {
  randomChance: runtimeRandomApi.randomChance,
});

const {
  LOG_LIMIT,
  getNutritionMax,
  getNutritionStart,
  clampNutritionValue,
  getHungerState,
  getHungerStateLabel,
  getHungerStateMessage,
  HUNGER_STATE,
  NUTRITION_COST_PER_ACTION,
  DAMAGE_PER_ACTION_WHILE_DYING,
} = appConfig;

let playDeathSound = null;
let saveHighscoreIfNeeded = null;
let showDeathModal = null;

const {
  countPotionsInInventory,
  countFoodInInventory,
} = createInventoryStatsApi({
  getState: () => state,
});

const runtimeSupportApi = createRuntimeSupportApi({
  getState: () => state,
  LOG_LIMIT,
  getNutritionMax,
  getNutritionStart,
  clampNutritionValue,
  getHungerState,
  getHungerStateMessage,
  HUNGER_STATE,
  NUTRITION_COST_PER_ACTION,
  DAMAGE_PER_ACTION_WHILE_DYING,
  showFloatingText: (...args) => runtimeActionsApi.runtimeBindings.showFloatingText(...args),
  getPlayDeathSound: () => playDeathSound,
  getSaveHighscoreIfNeeded: () => saveHighscoreIfNeeded,
  getShowDeathModal: () => showDeathModal,
});

const runtimeContext = createRuntimeContext({
  factories: appFactories,
  config: appConfig,
  ui: appUi,
  runtime: {
    getState: () => state,
    setState: (nextState) => {
      state = nextState;
    },
    getCurrentFloorState: runtimeSupportApi.getCurrentFloorState,
    addMessage: runtimeSupportApi.addMessage,
    renderSelf: (...args) => runtimeActionsApi.render(...args),
    randomChance: runtimeRandomApi.randomChance,
    randomInt: runtimeRandomApi.randomInt,
    createRuntimeId,
    createGrid,
    carveRoom,
    carveTunnel,
    roomsOverlap,
    clamp,
    rollPercent: runtimeRandomApi.rollPercent,
    getHungerStateLabel,
    ...runtimeActionsApi.runtimeBindings,
    getShowcaseAt: (...args) => runtimeActionsApi.getShowcaseAt(...args),
    maybeTriggerShowcaseAmbience: (...args) => runtimeActionsApi.maybeTriggerShowcaseAmbience(...args),
    healPlayer: (...args) => healPlayer(...args),
    refreshNutritionState: (...args) => runtimeSupportApi.refreshNutritionState(...args),
    grantExperience: (...args) => grantExperience(...args),
    createDeathCause: (...args) => createDeathCause(...args),
    saveHighscoreIfNeeded: () => saveHighscoreIfNeeded(),
    noteMonsterEncounter: runtimeSupportApi.noteMonsterEncounter,
    restoreNutrition: runtimeSupportApi.restoreNutrition,
    applyItemStatMods,
    applyPlayerNutritionTurnCost: runtimeSupportApi.applyPlayerNutritionTurnCost,
    countPotionsInInventory,
    countFoodInInventory,
    setRandomSequence: runtimeRandomApi.setRandomSequence,
    clearRandomSequence: runtimeRandomApi.clearRandomSequence,
    syncStartModalControls: (...args) => syncStartModalControls(...args),
    closeStartModal: (...args) => closeStartModal(...args),
    returnToStartScreen: (...args) => returnToStartScreen(...args),
  },
  equipment: {
    createBareHandsWeapon,
    cloneOffHandItem,
    getMainHand,
    getOffHand,
    getCombatWeapon,
  },
});

Object.assign(runtimeContext.core, assembleCoreModules(runtimeContext));
playDeathSound = runtimeContext.core.playDeathSound;
saveHighscoreIfNeeded = runtimeContext.core.saveHighscoreIfNeeded;

const {
  formatRarityLabel,
  generateEquipmentItem,
  getItemModifierSummary,
  getWeaponConditionalDamageBonus,
  itemHasModifier,
  playVictorySound,
  playLevelUpSound,
  playEnemyHitSound,
  playPlayerHitSound,
  playDodgeSound,
  playDoorOpenSound,
  playDoorCloseSound,
  playLockedDoorSound,
  playShowcaseAmbienceSound,
  playStepSound,
  buildTrapsForFloor,
  detectNearbyTraps,
  handleActorEnterTile,
  processContinuousTraps,
  createEnemy,
  createWeaponPickup,
  createOffHandPickup,
  createChestPickup,
  createFoodPickup,
  createKeyPickup,
  createDoor,
  rollChestContent,
  cloneWeapon,
  createDungeonLevel,
  updateVisibility,
  hasLineOfSight,
  isStraightShot,
  getDoorAt,
  isDoorClosed,
  getDoorColorLabels,
  canPlayerOpenDoor,
  openDoor,
  closeDoor,
  loadHighscores,
  loadHeroName,
  saveHeroName,
  loadHeroClassId,
  saveHeroClassId,
  saveOptions,
  hasSavedGame,
  getSavedGameMetadata,
  saveGame,
  loadSavedGame,
  clearSavedGame,
  loadLastHighscoreMarker,
  createDeathCause,
  xpForNextLevel,
  initializeGame,
  formatSavegameSummary,
  updateSavegameControls,
  saveCurrentGame,
  loadCurrentGame,
} = runtimeContext.core;

Object.assign(runtimeContext.presentation, createEquipmentPresentationHelpers({
  formatRarityLabel,
  getItemModifierSummary,
}));

const {
  formatWeaponStats,
  formatOffHandStats,
  getOffHandTooltipLines,
} = runtimeContext.presentation;

Object.assign(runtimeContext.interface, assembleInterfaceModules(runtimeContext));

const interfaceApi = runtimeContext.interface;
showDeathModal = interfaceApi.showDeathModal;

const {
  getPlayerCombatSummary,
  getActorStatusDisplay,
  getTopbarTooltipContent,
  bindTooltip,
  showTooltip,
  hideTooltip,
  hideDeathModal,
  restartRun,
  leaveToStartScreen,
  openRunStatsFromDeath,
  showChoiceModal,
  hideChoiceModal,
  showStairChoice,
  updatePotionChoiceSelection,
  cyclePotionChoice,
  cycleStairChoice,
  resolveChoiceBySlot,
  resolveStairChoice,
  toggleInventory,
  toggleRunStats,
  toggleOptions,
  toggleHelp,
  toggleHighscores,
  bindKeyboardInput,
} = interfaceApi;

const { bindInlineLoreTooltips } = createInlineLoreTooltipBinder({
  bindTooltip,
  showTooltip,
  hideTooltip,
  getLoreTooltip,
});

Object.assign(runtimeContext.gameplay, assembleGameplayModules(runtimeContext));

const {
  resolveBlock,
  resolveCombatAttack,
  healPlayer,
  gainLevel,
  grantExperience,
  attackEnemy,
  manhattanDistance,
  chebyshevDistance,
  hasNearbyEnemy,
  processSafeRegeneration,
  moveEnemies,
  tryPickupLoot,
  equipWeapon,
  canEquipOffHand,
  equipOffHand,
  moveToFloor,
  tryUseStairs,
  endTurn,
  tryCloseAdjacentDoor,
  movePlayer,
  handleWait,
  resolvePotionChoice,
  useInventoryItem,
  quickUsePotion,
  closeContainerLoot,
  takeSelectedContainerLoot,
  takeAllContainerLoot,
  getHealingConsumableGroups,
  getHealingOverlayState,
  selectHealingOverlayFamily,
  useHealingConsumableByFamily,
  selectTargetTile,
  syncTestApi,
} = runtimeContext.gameplay;

const showcaseAmbienceApi = createShowcaseAmbienceApi({
  getState: () => state,
  getCurrentFloorState: runtimeSupportApi.getCurrentFloorState,
  DISPLAY_CASE_AMBIENCE: appConfig.DISPLAY_CASE_AMBIENCE,
  randomInt: runtimeRandomApi.randomInt,
  addMessage: runtimeSupportApi.addMessage,
  showFloatingText: (...args) => runtimeActionsApi.runtimeBindings.showFloatingText(...args),
  playShowcaseAmbienceSound,
  playNarration: (text) => runtimeContext.core.playNarration(text),
});
runtimeActionsApi.bindShowcaseAmbienceApi(showcaseAmbienceApi);

const renderCycleApi = createRenderCycleApi({
  getState: () => state,
  syncTestApi,
  getPlayerCombatSummary,
  getCurrentStudioArchetypeId: runtimeSupportApi.getCurrentStudioArchetypeId,
  getCurrentFloorState: runtimeSupportApi.getCurrentFloorState,
  getCombatWeapon,
  updateVisibility,
  hideTooltip: interfaceApi.hideTooltip,
  renderBoard: interfaceApi.renderBoard,
  formatStudioWithArchetype: appConfig.formatStudioWithArchetype,
  depthTitleElement: appUi.depthTitleElement,
  playerPanelTitleElement: appUi.playerPanelTitleElement,
  getHeroClassAssets: appConfig.getHeroClassAssets,
  topbarHpElement: appUi.topbarHpElement,
  topbarLevelElement: appUi.topbarLevelElement,
  topbarLevelFillElement: appUi.topbarLevelFillElement,
  topbarDamageElement: appUi.topbarDamageElement,
  topbarHitElement: appUi.topbarHitElement,
  topbarCritElement: appUi.topbarCritElement,
  topbarBlockElement: appUi.topbarBlockElement,
  topbarFoodElement: appUi.topbarFoodElement,
  topbarStatusSummaryElement: appUi.topbarStatusSummaryElement,
  targetModeHintElement: appUi.targetModeHintElement,
  healOverlayElement: appUi.healOverlayElement,
  healOverlayItemsElement: appUi.healOverlayItemsElement,
  healOverlayNameElement: appUi.healOverlayNameElement,
  healOverlayTypeElement: appUi.healOverlayTypeElement,
  healOverlayEffectElement: appUi.healOverlayEffectElement,
  openTargetModeButton: appUi.openTargetModeButton,
  confirmTargetModeButton: appUi.confirmTargetModeButton,
  xpLabelElement: appUi.xpLabelElement,
  xpFillElement: appUi.xpFillElement,
  nutritionStateElement: appUi.nutritionStateElement,
  playerStatusSummaryElement: appUi.playerStatusSummaryElement,
  topbarFoodCardElement: appUi.topbarFoodCardElement,
  getActorStatusDisplay,
  getHealingConsumableGroups,
  getHealingOverlayState,
  selectHealingOverlayFamily,
  useHealingConsumableByFamily,
  getHungerStateLabel,
  HUNGER_STATE: appConfig.HUNGER_STATE,
  renderPlayerSheet: interfaceApi.renderPlayerSheet,
  renderEnemySheet: interfaceApi.renderEnemySheet,
  renderInventory: interfaceApi.renderInventory,
  renderHighscores: interfaceApi.renderHighscores,
  renderRunStats: interfaceApi.renderRunStats,
  renderStudioTopology: interfaceApi.renderStudioTopology,
  renderLog: interfaceApi.renderLog,
  boardElement: appUi.boardElement,
  boardViewportElement: appUi.boardViewportElement,
  boardScalerElement: appUi.boardScalerElement,
  startScreenElement: appUi.startScreenElement,
  gameHeaderElement: appUi.gameHeaderElement,
  startFreshRunButton: appUi.startFreshRunButton,
  inventoryModalElement: appUi.inventoryModalElement,
  inventoryItemsPanelElement: appUi.inventoryItemsPanelElement,
  inventoryHeroPanelElement: appUi.inventoryHeroPanelElement,
  studioTopologyModalElement: appUi.studioTopologyModalElement,
  runStatsModalElement: appUi.runStatsModalElement,
  debugInfoModalElement: appUi.debugInfoModalElement,
  optionsModalElement: appUi.optionsModalElement,
  savegamesModalElement: appUi.savegamesModalElement,
  helpModalElement: appUi.helpModalElement,
  highscoresModalElement: appUi.highscoresModalElement,
  startModalElement: appUi.startModalElement,
  gameShellElement: appUi.gameShellElement,
  stairsModalElement: appUi.stairsModalElement,
  deathModalElement: appUi.deathModalElement,
  toggleStepSoundElement: appUi.toggleStepSoundElement,
  toggleDeathSoundElement: appUi.toggleDeathSoundElement,
  toggleVoiceAnnouncementsElement: appUi.toggleVoiceAnnouncementsElement,
  toggleDecorativeOverlaysElement: appUi.toggleDecorativeOverlaysElement,
  toggleDecorativeOverlayDebugLogElement: appUi.toggleDecorativeOverlayDebugLogElement,
  toggleDecorativeOverlayDebugMaskElement: appUi.toggleDecorativeOverlayDebugMaskElement,
  showcaseAnnouncementModeElement: appUi.showcaseAnnouncementModeElement,
  uiScaleRangeElement: appUi.uiScaleRangeElement,
  uiScaleValueElement: appUi.uiScaleValueElement,
  studioZoomRangeElement: appUi.studioZoomRangeElement,
  studioZoomRangeValueElement: appUi.studioZoomRangeValueElement,
  tooltipScaleRangeElement: appUi.tooltipScaleRangeElement,
  tooltipScaleValueElement: appUi.tooltipScaleValueElement,
  studioZoomValueElement: appUi.studioZoomValueElement,
  enemyPanelModeElement: appUi.enemyPanelModeElement,
  toggleEnemyPanelModeButtonElement: appUi.toggleEnemyPanelModeButtonElement,
  inventoryItemsTabButtonElement: appUi.inventoryItemsTabButtonElement,
  inventoryHeroTabButtonElement: appUi.inventoryHeroTabButtonElement,
  openDebugInfoButtonElement: appUi.openDebugInfoButtonElement,
  updateSavegameControls,
  collapsibleCards: appUi.collapsibleCards,
  updatePotionChoiceSelection,
  refreshContainerLootModal: interfaceApi.refreshContainerLootModal,
  refreshDebugInfoModal: interfaceApi.refreshDebugInfoModal,
  chebyshevDistance,
  hasLineOfSight,
  isStraightShot,
});
runtimeActionsApi.setRender(renderCycleApi.render);

const {
  toggleCardCollapse,
  setInventoryFilter,
  setUiScale,
  setStudioZoom,
  adjustStudioZoom,
  resetStudioZoom,
  setTooltipScale,
  setEnemyPanelMode,
  toggleEnemyPanelMode,
} = createUiPreferencesApi({
  getState: () => state,
  renderSelf: (...args) => runtimeActionsApi.render(...args),
});

const {
  syncStartModalControls,
  openStartModal,
  closeStartModal,
  returnToStartScreen,
  applyStartProfile,
} = createStartFlowApi({
  HERO_CLASSES: appConfig.HERO_CLASSES,
  getHeroClassAssets: appConfig.getHeroClassAssets,
  classOptionsElement: appUi.classOptionsElement,
  heroNameInputElement: appUi.heroNameInputElement,
  saveHeroNameButtonElement: appUi.saveHeroNameButtonElement,
  heroIdentityStatusElement: appUi.heroIdentityStatusElement,
  loadHeroName,
  loadHeroClassId,
  saveHeroName,
  saveHeroClassId,
  initializeGame,
  getState: () => state,
  renderSelf: (...args) => runtimeActionsApi.render(...args),
  focusGameSurface: appUi.focusGameSurface,
});

const { bindAppControls } = createUiBindingsApi({
  choiceDrinkButton: appUi.choiceDrinkButton,
  choiceStoreButton: appUi.choiceStoreButton,
  choiceLeaveButton: appUi.choiceLeaveButton,
  containerLootTakeSelectedButton: appUi.containerLootTakeSelectedButton,
  containerLootTakeAllButton: appUi.containerLootTakeAllButton,
  containerLootCloseButton: appUi.containerLootCloseButton,
  containerLootCloseHeadButton: appUi.containerLootCloseHeadButton,
  stairsConfirmButton: appUi.stairsConfirmButton,
  stairsStayButton: appUi.stairsStayButton,
  openInventoryButton: appUi.openInventoryButton,
  openHeroDetailsButton: appUi.openHeroDetailsButton,
  inventoryItemsTabButtonElement: appUi.inventoryItemsTabButtonElement,
  inventoryHeroTabButtonElement: appUi.inventoryHeroTabButtonElement,
  openStudioTopologyButton: appUi.openStudioTopologyButton,
  openTargetModeButton: appUi.openTargetModeButton,
  confirmTargetModeButton: appUi.confirmTargetModeButton,
  closeInventoryButton: appUi.closeInventoryButton,
  openDebugInfoButtonElement: appUi.openDebugInfoButtonElement,
  closeStudioTopologyButton: appUi.closeStudioTopologyButton,
  saveGameQuickButtonElement: appUi.saveGameQuickButtonElement,
  openRunStatsButton: appUi.openRunStatsButton,
  closeRunStatsButton: appUi.closeRunStatsButton,
  openOptionsButton: appUi.openOptionsButton,
  closeOptionsButton: appUi.closeOptionsButton,
  closeSavegamesButtonElement: appUi.closeSavegamesButtonElement,
  openHighscoresButton: appUi.openHighscoresButton,
  closeHighscoresButton: appUi.closeHighscoresButton,
  openHelpButton: appUi.openHelpButton,
  closeHelpButton: appUi.closeHelpButton,
  helpOverviewTabButtonElement: appUi.helpOverviewTabButtonElement,
  helpControlsTabButtonElement: appUi.helpControlsTabButtonElement,
  showControlsHelpButtonElement: appUi.showControlsHelpButtonElement,
  showOverviewHelpButtonElement: appUi.showOverviewHelpButtonElement,
  openDeathKillsButton: appUi.openDeathKillsButton,
  closeDeathButton: appUi.closeDeathButton,
  copyDebugInfoButtonElement: appUi.copyDebugInfoButtonElement,
  closeDebugInfoButtonElement: appUi.closeDebugInfoButtonElement,
  startNewGameButton: appUi.startNewGameButton,
  loadGameFromLandingButtonElement: appUi.loadGameFromLandingButtonElement,
  openHighscoresLandingButton: appUi.openHighscoresLandingButton,
  openHelpLandingButton: appUi.openHelpLandingButton,
  startFreshRunButton: appUi.startFreshRunButton,
  inventoryFilterButtons: appUi.inventoryFilterButtons,
  collapsibleCards: appUi.collapsibleCards,
  zoomOutBoardButtonElement: appUi.zoomOutBoardButtonElement,
  zoomResetBoardButtonElement: appUi.zoomResetBoardButtonElement,
  zoomInBoardButtonElement: appUi.zoomInBoardButtonElement,
  cancelStartModalButtonElement: appUi.cancelStartModalButtonElement,
  uiScaleRangeElement: appUi.uiScaleRangeElement,
  studioZoomRangeElement: appUi.studioZoomRangeElement,
  tooltipScaleRangeElement: appUi.tooltipScaleRangeElement,
  toggleStepSoundElement: appUi.toggleStepSoundElement,
  toggleDeathSoundElement: appUi.toggleDeathSoundElement,
  toggleVoiceAnnouncementsElement: appUi.toggleVoiceAnnouncementsElement,
  toggleDecorativeOverlaysElement: appUi.toggleDecorativeOverlaysElement,
  toggleDecorativeOverlayDebugLogElement: appUi.toggleDecorativeOverlayDebugLogElement,
  toggleDecorativeOverlayDebugMaskElement: appUi.toggleDecorativeOverlayDebugMaskElement,
  showcaseAnnouncementModeElement: appUi.showcaseAnnouncementModeElement,
  enemyPanelModeElement: appUi.enemyPanelModeElement,
  toggleEnemyPanelModeButtonElement: appUi.toggleEnemyPanelModeButtonElement,
  viewDeathStudioButton: appUi.viewDeathStudioButton,
  startFormElement: appUi.startFormElement,
  bindTooltip,
  bindInlineLoreTooltips,
  topbarHpCardElement: appUi.topbarHpCardElement,
  topbarLevelCardElement: appUi.topbarLevelCardElement,
  topbarDamageCardElement: appUi.topbarDamageCardElement,
  topbarHitCardElement: appUi.topbarHitCardElement,
  topbarCritCardElement: appUi.topbarCritCardElement,
  topbarBlockCardElement: appUi.topbarBlockCardElement,
  getTopbarTooltipContent,
  resolveChoiceBySlot,
  closeContainerLoot,
  takeSelectedContainerLoot,
  takeAllContainerLoot,
  resolveStairChoice,
  toggleInventory,
  toggleStudioTopology: interfaceApi.toggleStudioTopology,
  toggleRunStats,
  toggleOptions,
  toggleSavegames: interfaceApi.toggleSavegames,
  toggleHelp,
  toggleHighscores,
  toggleDebugInfo: interfaceApi.toggleDebugInfo,
  copyDebugInfo: interfaceApi.copyDebugInfo,
  restartRun,
  leaveToStartScreen,
  openRunStatsFromDeath,
  hideDeathModal,
  toggleCardCollapse,
  setInventoryFilter,
  setUiScale,
  setStudioZoom,
  adjustStudioZoom,
  resetStudioZoom,
  setTooltipScale,
  setEnemyPanelMode,
  toggleEnemyPanelMode,
  saveCurrentGame,
  getState: () => state,
  saveOptions,
  openStartModal,
  closeStartModal,
  applyStartProfile,
  cycleTargetMode: (...args) => runtimeContext.gameplay.cycleTargetMode?.(...args),
  enterTargetMode: (...args) => runtimeContext.gameplay.enterTargetMode?.(...args),
  cancelTargetMode: (...args) => runtimeContext.gameplay.cancelTargetMode?.(...args),
  confirmTargetAttack: (...args) => runtimeContext.gameplay.confirmTargetAttack?.(...args),
  bindKeyboardInput,
  helpOverviewPanelElement: appUi.helpOverviewPanelElement,
  helpControlsPanelElement: appUi.helpControlsPanelElement,
});

const { bootstrapApp } = createAppBootstrap({
  bindAppControls,
  initializeGame,
  detectNearbyTraps,
  renderSelf: (...args) => runtimeActionsApi.render(...args),
  syncStartModalControls,
});

bootstrapApp();
